### ISSUE TITLE
Disappearance of npc after reboot

### ISSUE THREAD

**Issue by aurel85** [PaperMC/Paper#1197]
Hi,

**### What behaviour is expected:**

Just my npc in their enclosure :D

**### What behaviour is observed:**

After a reboot, some players lose their npc stored in their database. I thought it was the fault of the plugin MobFarmManager following an update of this plugin but returning to the previous version the bug is still present so I wonder if it is not related to PaperSpigot that I also updated at the same time.

**### Steps/models to reproduce:**

There is nothing in the console or other apparent error, just npc that disappear for no reason during a reboot.

**### Plugin list:**

https://www.dropbox.com/s/biwndafa235qex4/Capture.PNG?dl=0

**### Paper build number:**

https://www.dropbox.com/s/c8fy7a47rz9htda/Capture2.PNG?dl=0

**### Anything else:**

I also notified the developer of MobFarmManager for this bug but it is unlikely that it comes from his plugin finally.
https://www.spigotmc.org/threads/mob-farm-manager-supports-1-7-10-up-to-1-12-hopper-support-paid.106779/page-7#post-3062221

Thank you in advance.

**Comment by electronicboy** [comment]
"pnj"?

**Comment by aurel85** [comment]
Sorry, pnj = npc in french
I modified.

**Comment by disqetow** [comment]
My npc lost too.

**Comment by aikar** [comment]
ok I've modified the new code in a way that really should be guaranteed the same behavior as pre optimization, so the issue should be resolved.

I've also had weird bugs on my server too that I have to associate with this also, and hopefully will now be fixed.

Paper build 1490

**Comment by aurel85** [comment]
Despite version 1490 the players of my server continue to have disappearances of entities (sheep, cows...)

**Comment by Cryptite** [comment]
I can confirm this does not fix the NPCs issues as well. It seems to affect NPCs which are despawned and spawned manually by the API. On our instance, any NPCs that are permanently on show just fine, but the call to spawn them doesn't seem to work as far as players seeing the entity.

**Comment by aikar** [comment]
Can you try 1481

**Comment by Cryptite** [comment]
Does seem to be functioning in 1481
