### ISSUE TITLE
Mobs vanishing when going from build 1468 to 1500

### ISSUE THREAD

**Issue by LogGits** [PaperMC/Paper#1208]
Going from build 1468 to 1499 causes mobs to vanish. I have no idea how to reproduce this.

I just teleported into an unloaded chunk (an offline users base) and all their mobs are gone.

Was also mentioned in #1199.

Though i suspect it could be related to StackMob as:
- Villagers
- Some named mobs
- Llamas with carpet on them
- Horses types

Things that didn't vanish:
- Cows
- Pigs
- Chickens
- Sheep (including coloured)

As I mentioned before i don't think this is related to PaperSpigot, I am just writing this to ask if anything relating to entity checks changed that could have affected StackMob to break this. Once again, I am not entirely sure as to the cause of the vanishing mobs, I am just trying to get as much info as I can to resolve my issue.

**EDIT: It is not caused by stackmob. I did a test with stackmob disabled and still lost mobs.**

### Plugin list:
AAC, ChatControl pro, Citizens, CommandNPC, DeluxeMenus, Essentials, FastAsyncWorldEdit, HolographicDisplays, LeaderHeads, LiteBans, LuckPerms, PlaceholderAPI, ProtocolLib, Vault, WorldEdit, WorldGuard, WorldGuardExtraFlags, StackMob, CMI, React.

### Paper build number:
1499

**Comment by zachbr** [comment]
I'm just going to re-open the last ticket since this may still be a problem.
Thanks

**Comment by aikar** [comment]
Fixed in build 1500. Finally found the source of this final detail while doing the 1.13 update.

**Comment by LogGits** [comment]
Ok i tried on 1500 and for some reason it is still happening. A group of ~30 villagers vanished. Found out its not related to stackmob, I did tests without stackmob on the server and they still vanished.

**EDIT: This actually could be fixed. Im trying to find a way to reproduce.**

**EDIT 2: Yeah I think it is fixed. Great work guys** 👍

**Comment by aikar** [comment]
@LogGits anything saved on an older build would of still potentially been bugged, but it shouldn't happen any more going forward.

What the source was, any entity that was default not persistent (mobs), that was made persistent (name tags, picking up armor), and various other conditions that makes a mob turn persistent when they normally wouldn't be, triggered some code that put those entities in a weird state that they likely just wasn't being saved to the chunk.

**Comment by LogGits** [comment]
Ok I am actually still having this issue on build 1500. Same entities vanishing. This time everyone is reporting them vanishing.

- Pigs, Sheep, Cows are fine.

**Comment by aikar** [comment]
@LogGits Ok I'm fairly confident this is caused by the issue described in #1223 - please subscribe to that issue.

**Comment by aikar** [comment]
@LogGits can you go to latest build and confirm for sure it does still happen?

What's odd is that 1468 to the one concerned patch has nothing to do with entity issues...
however, I had hologram loss ever before that patch was added, so I know the issue is not that patch.

But the suspected patch in #1223 was build 1448....

I'm getting lost as to the source of the issue, as I can't see why the suspect in #1223 could be it either.

**Comment by LogGits** [comment]
@aikar Yeah it happens on 1500. At first everything seemed fine, then i hopped offline and a few players were playing and spammed me in discord telling me that their mobs vanished. I joined and they did indeed vanish.

A user let me use their base as a test for 1491+ (a constant). I would replace their mobs after they vanished. I replaced them before 1500 update. Mobs were still there, nothing was affecting them while i was on roaming around. Then after I went offline players reported that the mobs vanished. I checked and they did vanish, even in the test base.

I don't know what is the latest safe build to use, but i was previously on 1468 and i didn't want to test with any newer versions incase it happens again. Hence, this is the reason i got back to 1468.

I have a hypothesis, (could be wrong), I have two plugins that i think *could* be causing it. React and StackMob. My theory is that StackMob could be failing a check to stack the mob and then deleting the mob. The other theory is that React could be messing with chunks and entity loading (not sure about this theory).

**Comment by aikar** [comment]
can you try to reproduce the scenario occurring on your server with no plugins and come up with easier to trigger reproduce steps? I have no idea how to trigger it currently.

Just every few days holograms disappear, but not ALL holograms, its very inconsistent.

**Comment by LogGits** [comment]
Yeah thats the case for me. Mobs would despawn but it wasn't consistent.

A user over on the React discord suggested that i use:

```yaml
skip-entity-ticking-in-chunks-scheduled-for-unload: false
```

So I'll try this first to see of this has anything to do with it. If not il remove all plugins except for a few key plugins and try that way.

**Comment by LogGits** [comment]
Ok i have been testing with skip-entity-ticking... as false and disabled react, stackmob, and shopkeepers and i can now somewhat reproduce. I will provide a video shortly.

**Comment by LogGits** [comment]
-- edit: moved to #1223 --
