### ISSUE TITLE
Light bug - random dark patches

### ISSUE THREAD

**Issue by Decme** [PaperMC/Paper#1542]
Since migrating from Spigot to Paper, we've been seeing some odd lighting.

http://oi68.tinypic.com/24bra8n.jpg
http://oi65.tinypic.com/9lewsz.jpg

Plugins:
CoreProtect, DiscordSRV, ChadEx, Dynmap, Dynmap Worldguard, EssentialsX, NameColors, OnDeathCoord, PermissionsEx, Vault, VillageMarker

Paper build number:
342

Other comments: These lighting issues are visible with or without optifine. Players are reporting that the actual light levels are affected too, which causes mobs to spawn in what are meant to be fully lit areas.

**Comment by aikar** [comment]
Do you have light queue enabled in your paper.yml under world settings? If so, try turning that off.

We just fixed some light bugs last night. It's very possible this is from before the fix.

Please let us know if you see NEW cases of this pop up. IE Something that wasnt dark before, randomly became dark, while light queue was turned off.

Will need steps on how to reproduce it.

**Comment by Decme** [comment]
queue-light-updates: false

I will try again tomorrow with a newer build if there is a new one out & see how it goes.

**Comment by aikar** [comment]
youll have to place blocks to fix existing bugged areas. but hopefully shouldn't see NEW issues arise.

**Comment by Darunox** [comment]
Hello, 
we found that the problem appears in a particular case.

1st image the quartz blocks are in this position in 1.12.2.
http://zupimages.net/viewer.php?id=18/41/m9gd.png

After the conversion in 1.13.1 of this chunk the blocks are now in column like this.
http://zupimages.net/viewer.php?id=18/41/bkea.png 

After a disconnection and reconnection the beug appears.
http://zupimages.net/viewer.php?id=18/41/4yau.png

The problem is independent of optifine.

After creation of one cube with /fill wall by wall. 
https://imgur.com/a/GVd9Zxf

Plugins : 
CoreProtect, Essentials*, EssentialsChat*, EssentialsSpawn*, GriefPrevention, Multiverse-Core*, Multiverse-Portals*, PermissionsEx*, SysInfoPlugin*, Vault*, WorldEdit, WorldGuard, XRayHunter

Last update Paper build number: 349 

Thank you in advance for your answer.

**Comment by aikar** [comment]
Please provide region files exhibiting the problem.
If it's at your spawn near 0,0, that would be `world/region/r.0.0.mca` but you can provide `r.1.0, r.0.1, r.-1.0, r.0.-1` too

**Comment by Darunox** [comment]
in response for this issue https://github.com/PaperMC/Paper/issues/1549

Here are the region files

The first file is for the first situation with the quartz blocks :
https://drive.google.com/open?id=1yvMjFKU2mHYhrGhJABgi7iRKwTD-JnQM

for the second this file :
https://drive.google.com/open?id=1YPftnArFKrfP85Y8tutj1C-AljXLetYW

**Comment by Decme** [comment]
I confirm the bug still exists since 352 update, dug out a whole new chunk after the update and the lighting bug appears in the newly dug area. Sorry don't have region files yet but can upload tomorrow if you still need more.

**Comment by aikar** [comment]
@Darunox what's coordinates?
nvm found it.

**Comment by aikar** [comment]
When I break the block and replace it, it fixes the light. Can you record a gif of or something?

**Comment by Darunox** [comment]
The exact coordinates are 3340 -4422 for the first problem and -2361 2329 for the second.

For the first bug, if you replace the block you don't have the shadow immediatly but if you disconnect and reconnect the shadows appears, again and again and again.

But for the second you can find this bug on several chunk around this coordinates.

With my 3 images on the report https://github.com/PaperMC/Paper/issues/1549 you have a little gif but if it's not clear i can try to make a gif.

**Comment by aikar** [comment]
Ok finally a bug I can reproduce.... that logging out bit was important. Looking into it now.

**Comment by Darunox** [comment]
Perfect ! Sorry for my english x) ! 
You think you can be easy to fix?

Thank you for all the work you do;).

**Comment by aikar** [comment]
@Darunox I'm only seeing this issue the first time the chunk loads. Once it unloads and reloads, it appears fixed? Does it keep happening for you?

**Comment by Darunox** [comment]
yes this problem is recurrent for all the blocks posed before the conversion of the chunks in 1.13.1 and when one makes a command to add block (/ fill).

At each logout and log in you detect this problem despite adding a block instead of the bug and remove it later.

This is not the only player on our server who complains about this light beug even if it is the only one we tell you.

Gif for this bug :
<a href="http://www.noelshack.com/2018-41-2-1539044056-bug-light.gif"><img src="http://image.noelshack.com/minis/2018/41/2/1539044056-bug-light.png" border="0" alt="1539044056-bug-light.gif - envoi d'image avec NoelShack" title="1539044056-bug-light.gif"/></a>

**Comment by aikar** [comment]
Ok I've got it figured out, fix coming in a min

**Comment by Darunox** [comment]
Thank you very much ! For all players on our server ! :)

**Comment by aikar** [comment]
The fact the client fake fixes the light really made it hard to see an issue when testing an optimization I made, and combine with the fact that it seems to fix itself on chunk reload.... but I see I misunderstood one section of code I changed so reverting it.

**Comment by Darunox** [comment]
I'm going to see with my colleague to update when the correction goes out and I'll come back to you to tell you if the beug persist on our server or not.

**Comment by aikar** [comment]
build 353+

**Comment by Darunox** [comment]
The beug is fixed with the new update.

Only problem we have to update each area by hand which will take us a lot of time.

Thank you very much for bringing this correction very quickly :)!

**Comment by Decme** [comment]
Still broken as of release 355: http://oi67.tinypic.com/1268j1y.jpg
How do I find the region file for this location?

**Comment by aikar** [comment]
@Decme this is something new that showed up? what did you do to cause it?

If this is a spot you "found", note that previously caused areas will not self repair.

I'm not able to reproduce any more issues with light now...

**Comment by Decme** [comment]
Yeah it was new. We dug out another chunk after updating to release 355 in which the light bug was said to be fixed, and the dark shadows appear as in the above screenshot. I can offer the region files if that will help, just need to know which ones to look for, for these coordinates.

**Comment by electronicboy** [comment]
Could you please try enabling random light updates in spigot.yml if you've got it disabled? 

I recall seeing several issues around this going back a long time, and with 1.13 they kinda spiked a bit due to this feature in spigot, the upside is you don't have the performance hit of updating chunk lighting properly and consistently, downside is that you intentionally allow chunks to become incorrect in regards to their lighting, which breaks various things on the server such as mob spawns, I'm not sure if aikar tests with this on/off, but I figured that this was worth noting, especially given that I've seen reports of this very issue in spigot
