### ISSUE TITLE
PaperAsyncChunkProvider::requestChunk is slowing down monster pathfinding

### ISSUE THREAD

**Issue by hurrgurl** [PaperMC/Paper#1625]
git-Paper-405 (default paper.yml & spigot.yml)

No notable plugins, mostly vanilla. This is the biggest 1.13 lag issue I have found so far.

https://i.imgur.com/xZTnPgm.png

https://sparkprofiler.github.io/?JlZ1l0NHWZ

This happens presumably because the entities are trying to pathfind through unloaded/ungenerated chunks that the pathfinders expected to be loaded and in use.

**Comment by electronicboy** [comment]
Should be fixed in build 406+

**Comment by hurrgurl** [comment]
Same issue still happening at 406

https://sparkprofiler.github.io/?XVibOfuFNI

**Comment by electronicboy** [comment]
There was technically two issues here, 
1) The server can get stuck behind loading other chunks, blocking the main thread - this was fixed (you're definitely waiting less behind requestChunk now)
2) pathfinders loading chunks in general - This I was supposed to create a new issue about, mainly as I want a central point for us to be able to track these

**Comment by hurrgurl** [comment]
Please point me to the right place once you make a new issue. I'm not very good at finding things.
