### ISSUE TITLE
Teleportation sending players to wrong area when warping.

### ISSUE THREAD

**Issue by Castiella** [PaperMC/Paper#1889]
https://github.com/EssentialsX/Essentials/issues/2445

**Comment by aikar** [comment]
As said on ticket, fixed in Paper 554+, please update

**Comment by Castiella** [comment]
i am now using the recent build of paper and its still happening.

**Comment by Castiella** [comment]
(Using 561)

**Comment by electronicboy** [comment]
Cannot replicate,

created a warp called "test", created a flat world and tp'd to 1000 100 1000, `/warp test` and I'm back where I was

**Comment by Castiella** [comment]
Would you like to come onto my server and check it out? I can op you and everything.

**Comment by Castiella** [comment]
i'd like to clarify, you have to move worlds for it to happen.
For example,
Set the warp, move around within the same world.
Warp/mvtp to a different world.
warp back to /warp test 
**you are back where you last were in the test world, not the warp**

**Comment by Castiella** [comment]
Well,  I removed everything but Essentials, LuckPerms and Multiverse as suggested by Aikar -  and it worked.

**HOWEVER**

I took the time to add each of my plugins one at a time,  **ANY** of the following plugins, the error occurred.

Ban Managment - https://dev.bukkit.org/projects/ban-management
Async World Edit - https://www.spigotmc.org/resources/asyncworldedit.327/
Bannerboard - https://www.spigotmc.org/resources/bannerboard.20435/
BlackSmith

**Plugins that didnt effect it:**
Razz's Minigames
Chest Shop
     Chest Shop Notifer
Citizens (Premium)
Coloured Anvils
Coloured Signs
Colour Shuffle
Colour MOTD
Console Say
CoreProtect, WorldGuard & World Edit
CrazyCrates
CrazyEnchantments
EditableSign
EnchantsPlus
EnjinMinecraftPlugin
FirstJoinPlus
HeadDatabase
HolographicDisplays
HolographicScoreboard
LagAssist 
JumpBlocks
LibsDisguises (Premium)
LobbyPresents
MiniaturePets
MobArena
LWC
NuVotifer
OfflinePay
PlayerVaults
PlayerVaultsMultiWorld
PlugMan
ProtocolLib
PostPidgeon
Ridables
Quests
SimpleVoteListener
SavageDeathChests
SimpleSit
Vault
VanishNoPacket
SuperTrails
VotingPlugin
ArtMap
AncientGates

**Furthermore, I then reinstalled all of the plugins in the error list once I added ones on the okay list , the glitch did not persist.**

I am well and truly stumped as to how deleting the plugins and then reinstalling them from the same files has fixed the error. I will comment shortly if the issue persists once more.

**Comment by Castiella** [comment]
Okay, so looks like i was wrong this just happened:

>Warped to the Minigames world spawn
>Warped to a Minigame area within the same world
>Was taken to the last world I visited.

Now I am stumped even more than before.

**Comment by electronicboy** [comment]
`I am well and truly stumped as to how deleting the plugins and then reinstalling them from the same files has fixed the error`

Plugin load/enable order, depends on the OS you're using as to how the files are returned back from the filesystem, but on some OSes, moving files around, etc; Can change the order that java sees the files, in which changes the order that plugins are enabled in and the order that their listeners are registered

**Comment by Castiella** [comment]
So now i am starting again, removing all of the plugins that cause this new error.

Here goes something.

**Comment by Castiella** [comment]
So do you think the issue is to do with the OS and not the plugins themselves?

**Comment by electronicboy** [comment]
No, the OS is fine, just the behavior of the OS means that whatever misbehaving plugin is going to be interacting at a different time during events, etc; Often times this can lead to people finding stuff randomly fixed after doing the whole "move the plugins out and add them back in one by one", or they do stuff like updating a plugin and all of a sudden not even rolling the plugin back fixes the issue

**Comment by Castiella** [comment]
Oh boy :( So its definitely one of the ones i originally listed? or could it be literally any? What advice can you give me to do next?

**Comment by electronicboy** [comment]
You could try shuffling plugins even more in hopes that you find the common denominator, or look into basically finding somebody who can dig a bit better to find what's causing it

**Comment by Castiella** [comment]
i dont suppose you could point me in the direction of someone i can commission for it? I've asked two developers and they don't understand it.

**Comment by Castiella** [comment]
Turned out to be Multiverse-Inventories causing it.

**Comment by Castiella** [comment]
Okay,  update, a developer told me it was inventories.

I have just attempted to recreate it on my server, and i didn't replicate it correctly last time. i am now able to replicate this glitch on my server with just essentials and multiverse installed.

Please advise further?
