### ISSUE TITLE
Nametagged (or otherwise Persistent) mobs count towards mob cap

### ISSUE THREAD

**Issue by aeonlamb** [PaperMC/Paper#1922]
### What behaviour is expected:
Mobs that are nametagged or are otherwise made to be persistent (when they aren't ordinarily) should not count to their respective mob cap. For example, a nametagged sheep should not count towards the passive mob cap, or a zombie that has picked up an item and received the PersistenceRequired NBT tag should not count towards the hostile mob cap. 

The minecraft wiki [makes note of this behavior](https://minecraft.gamepedia.com/Name_Tag#Usage), although it fails to mention that this also applies to nametagged hostile mobs, as well as hostile mobs that are made persistent through some other means.

### What behaviour is observed:
On Paper, this behavior is broken- nametagged/persistent hostile mobs (in the case of my tests, nametagged endermen, and zombies given items to hold) prevented further mob spawns. 

This is NOT caused by the recent change to the mob spawning algorithm that was made in paper build 572. In fact, this affects even paper 1.12.2.

### Steps/models to reproduce:
The easiest way to reproduce this issue is in the end, due to how frequently endermen can spawn in a void environment. It should affect any and all mob spawning in theory, though.

1. Go out to the void in the end, make sure no other chunks around you are loaded where endermen could spawn, use /paper entity list to ensure there's no other endermen.
2. Make a platform at y:0 using /fill or some other means, doesn't matter how, just a platform of solid blocks. Make sure to spawn-proof it for now, with water, torches, whatever.
3. Make another platform of solid blocks nearby, separate from the first so that mobs cannot cross to the other platform.
4. Fly away and let endermen spawn on the 2nd platform until you reach mob cap. should be ~70 mobs with default settings, render distance 10. (Assuming you are testing in 1.13.2)
5. Come back, and ensure you are still at mob cap. Grab an anvil and a nametag, and nametag every last enderman. This can be annoying, but just spam right click on all of them as you fly around and you should get most of them.
6. After nametagging all of the enders on the 2nd platform, remove the spawn-proofing you did to the 1st platform, and fly far enough away to let mobs spawn on it.
7. Nothing should spawn on the 1st platform. This is the bug. The endermen you nametagged should be ignored when determining the mobcap of the world, but they are still counted.

### Plugin list:
None

### Paper build number:
Paper-588 (1.13.2).
Other versions tested: Paper-564 (1.13.2), Craftbukkit 1.13.2 (forget what version), Spigot 1.13.2 (Latest as of typing this), Paper-1610 (1.12.2).

As far as I can tell, this bug is specific to Paper. Both craftbukkit and spigot handle this the same as vanilla. The bug occurs in the latest 1.12 builds, the latest 1.13 builds, and even older 1.13 builds before the recent change to the mob cap mechanics in Paper.

### Anything else:
This is an issue for servers because certain players may rely on the vanilla behavior of nametagged mobs not counting toward the mob cap in order to keep pets in a certain area, such as near a mob farm etc, while still keeping them from actually affecting the spawn rates of a farm, or even of the rest of the server perhaps. Another example I can give is if some player happens to live in some huge underground base they never light up, and they let zombies pick up whatever random junk they toss around and let them hang out under there, the mobs could build up, preventing mob spawns for other players. Animal spawns are probably the biggest concern, though.

As I stated before, the recent change to the mob cap mechanics did NOT cause this bug, as it was present in Paper in earlier 1.13 builds and even in 1.12 builds. However, the new mechanics make it a bit easier to determine why this occurs now.

The problem now is simply that these nametagged mobs will always keep their spawn reason as `NATURAL`. As far as I can tell, the code that determines the mob cap now only checks to see whether or not the mob's spawn reason is `NATURAL`. If it is, it gets counted. If it isn't, it's not counted. Mobs that become persistent due to picking up items, being renamed with a nametag, etc. will always retain their spawn reason as `NATURAL` if that's how they originally spawned, meaning they'll always count, even though they shouldn't.

**Comment by aikar** [comment]
I think I saw what you was talking about when I worked on that recent change, but note:

```java
    public void updateEntityCount(Entity entity, int amt) {
        // Only count natural spawns so that mob
        if (!(entity instanceof IAnimal) || (
            !world.paperConfig.countAllMobsForSpawning &&
            entity.spawnReason != SpawnReason.NATURAL &&
            entity.spawnReason != SpawnReason.CHUNK_GEN
        )) return;

        if (entity instanceof EntityInsentient) {
            EntityInsentient entityinsentient = (EntityInsentient) entity;
            if (amt > 0 && entityinsentient.isTypeNotPersistent() && entityinsentient.isPersistent()) {
                return;
            }
        }

```

We do check for persistence, however it's only done at entity world add.

The issue is that if persistence state changes after its added to the world, the count is never decremented.

So I imagine in your reproduce steps, if you unload those entities and reload them all, the spawns would resume.

**Comment by aikar** [comment]
Fixed in 595+

**Comment by aeonlamb** [comment]
Thanks, I think you may have fixed this the wrong way though. It seems that animals pretty much spawn infinitely now. Don't need to nametag them or anything, regular animals just keep on spawning even if there's 100 others w/ a "natural" spawn reason... I don't think that's intended : P

I believe that in vanilla, animals specifically check if they have a CustomName applied (nametag), whereas hostile mobs just check the persistent tag. I think there might be a few special cases, like with ocelots, but I'm not sure. Kind of difficult to test in vanilla, since I can't modify the speed at which passive mobs will spawn there.

Also just for clarity, the animals did not spawn endlessly before that most recent patch (595).

**Comment by aikar** [comment]
Should be fixed now. Craft Bukkit messed with the persistent flag so it no longer matches vanilla :( restored their check

**Comment by aeonlamb** [comment]
Just tried it out with the latest build, and the animals spawning endlessly is fixed, which is a relief. However my original issue still stands for peaceful mobs. Nametagging an animal that is ordinarily persistent doesn't exempt it from the mob cap count, which differs from vanilla behavior. Obviously, matching vanilla behavior isn't entirely the goal with this change to the mob cap mechanics, but I think that it wouldn't hurt to keep a feature such as that. Thanks for looking into it either way though :)

**Comment by aikar** [comment]
Arg.... you know what. I think that perfectly describes what CraftBukkit breaks here.

The change I made fixes your issue yes by removing CB's crappy change, but causes the infinite spawn issue as you mentioned.

CB is setting persistence = true on all animals regardless of it being name tagged.

I'll see what I can do about it.

**Comment by Cooperating** [comment]
I've also encountered a similar bug where named hostile mobs will spawn infinitely in paper-597 1.13.2.  I use a plugin that spawns custom mobs with names and abilities, so all hostile mobs have names.  Not sure if I should make a separate issue report or if this issue is related.

**Comment by aikar** [comment]
@Cooperating you will need to turn the config count-all-mobs to true in paper.yml then. That is working as intended currently.

Alternatively, get that plugins author to spawn them with NATURAL reason.

**Comment by chrissamael** [comment]
I think I have encountered this bug on paper-160, MC 1.16.2, with Piglins in the nether - giving them a carved pumpkin or a name doesn't remove them from the per-player mob-cap - I'm assuming this is not intentional? :)
We have per-player-mob-cap enabled.

**Comment by cferreras** [comment]
> I think I have encountered this bug on paper-160, MC 1.16.2, with Piglins in the nether - giving them a carved pumpkin or a name doesn't remove them from the per-player mob-cap - I'm assuming this is not intentional? :)
> We have per-player-mob-cap enabled.

Same on 1.6.4

**Comment by cferreras** [comment]
> I think I have encountered this bug on paper-160, MC 1.16.2, with Piglins in the nether - giving them a carved pumpkin or a name doesn't remove them from the per-player mob-cap - I'm assuming this is not intentional? :)
> We have per-player-mob-cap enabled.

Same on 1.16.4

**Comment by Machine-Maker** [comment]
The piglin/hoglin specific issues were fixed in e14aff9b32500efd8dac8bcaa3f0676e01b332fb, but I believe this still remains an issue elsewhere. Will take redoing CB's mangling of the vanilla persistence mechanics over the years

**Comment by Owen1212055** [comment]
Cannot reproduce anymore. 

I am assuming that this was fixed sometime when spigot reverted a lot of their persistence changes (see: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/7bc728a6b873d800934b0fc32e173c1e2d801e59#src/main/java/org/bukkit/craftbukkit/event/CraftEventFactory.java)

Before any nametags:
![image](https://user-images.githubusercontent.com/23108066/183273808-0edc459f-5234-4422-99fa-33eaa8ae8846.png)
As nametags are added new enderman are spawned:
![image](https://user-images.githubusercontent.com/23108066/183273825-581e0de0-e1e2-4a31-a3f2-9c01088df4e2.png)
