### ISSUE TITLE
Passive Mobs don't move

### ISSUE THREAD

**Issue by lordrius** [PaperMC/Paper#2232]
Hi!

Trying 1.14.3 builds, i've noticed passive mobs don't move from their spots (Pigs, Sheeps, Fishes...)

Tried with 108, 109, 110 builds... With Spigot-4d2f30f-f1f3355 works fine. Clean setup environment, no plugins.

Can you reproduce and confirm the issue?

Thanks!

**Comment by QuantumToasted** [comment]
Can confirm, i'm on build 110 and I cannot get any passive mobs to move from where I spawn them. Haven't tested earlier builds.

**Comment by Darcion** [comment]
can confirm, passive mobs dont move

**Comment by Frerduro** [comment]
Can also confirm

**Comment by electronicboy** [comment]
It appears to be working fine here, got a bunch of sheep that I spawned in roaming around at the least

**Comment by Frerduro** [comment]
Try aquatic passive mobs its only happening with tropical fish and dolphins for me

**Comment by finlaysawyer** [comment]
Can also reproduce. Passive mobs are indeed frozen however when taming them, e.g. holding seeds for chickens they move just fine. They also rotate around on the spot just like normal but won't actually move, nor will they run away when hit.

**Comment by EliasLahham** [comment]
Wither skeletons aren't scared of tamed wolves either. I believe this might be related

**Comment by electronicboy** [comment]
Mind testing the latest build? Appears that this issue has been solved from some testing

**Comment by finlaysawyer** [comment]
Unfortunately this still doesn't seem to fix it for me. Tried with an upgraded 1.14.2 world with both previously and naturally spawned entities.

**Comment by lordrius** [comment]
Hi, thanks for the quick response @electronicboy !

I've tried latest 112 build testing animals movement and no changes...

Here is my video comparison:

Paperclip-112:
https://youtu.be/Cix2gCic8ww

Spigot:
https://youtu.be/TbEwmy1P5Sk

**Comment by kirkleon** [comment]
Hostile mobs inside a mob grinder also seem to be frozen (I am ~24 blocks away from them), I'm assuming this is a related issue. I'm on Paper 112

**Comment by Darcion** [comment]
tried #112 but still frozen animals

**Comment by DonSensiLeone** [comment]
Some mobs move (a very few) while most don't , no real changes between version 111 and 112 . Some mobs like cats in villages only move when you offer them some fish , then once tamed will move to some point, but won't really follow you. I had an iron golem wich didn't move at all until i punched him , then he started to run after me.. Most of the time mobs just spin around like shown in LordRius video (spigot & paper).

**Comment by BillyGalbreath** [comment]
Everyone having problems with this, please post your timings report (so we can see your config settings).

I am having trouble reproducing this. All mobs are normal for me.

I have a feeling it's something specific with how you guys are configuring your servers possibly creating an edge case where mobs wont move (probably view distance & EAR settings conflict, etc etc).

**Comment by lordrius** [comment]
Hi Billy!

Here is my **test server** timings, new world, new config files... Now using build 114.

https://timings.aikar.co/?id=d6a666d4c4a14233925137b6297454f9

And this from my **local backup server**:

https://timings.aikar.co/?id=d181e94ecc704a78b860dcf411d7ccef

https://youtu.be/EmAAEM7Ck-w

Thanks!

**Comment by lordrius** [comment]
Well, I have found a solution (for me), I'm going to list the steps i followed (it is very strange, remember 1.14.2 was working fine with these files...).

1) Delete bukkit.yml > Start server (new bukkit.yml created), no changes, mobs don't move. > Stop server.
2) Delete spigot.yml > Start server (new spigot.yml created), no changes, mobs don't move. > Stop server.
3) Delete paper.yml > Start server (new paper.yml created), mobs start moving! > Stop server.
4) Reconfigure bukkit.yml > Start server, working fine! > Stop server.
5) Reconfigure spigot.yml > Start server, working fine! > Stop server.
6) Reconfigure paper.yml > Start server, mobs don't move!! > Stop server.
7) Check paper.yml modified parameters > keep-spawn-loaded: true > false seems to be the problem (for me) reverted to true and works fine...
¯\\_(ツ)_/¯

**Comment by BillyGalbreath** [comment]
Yay troubleshooting \o/ ^_^

I'm not at PC to test, but if anyone else can confirm it's the `keep-spawn-loaded` setting, that'd be awesome ;)

**Comment by supertakeru** [comment]
Deleted and regenerated all three .yml files like he did, passive mobs (some squids) started moving again, while most others remained frozen. Whole time keep-spawn-loaded is set to true [believe it is default anyways?]

Timings you asked for:
https://timings.aikar.co/?id=cc20e89505284e6fa4c089786435f339

Paper 114

**Comment by DonSensiLeone** [comment]
i tried to make a whole new 1.14.3 world without these yml files from version 111 ,using version 112 ( configs are always optimized as advised here : https://www.spigotmc.org/threads/guide-server-optimization%E2%9A%A1.283181/ ) , now they do move , with lots of lags though but they do move, without any plugins or even with . In my last message i used version 111 (mobs didn't move) and i just tried to use version 112 without creating a new world .. didn't work and i didn't save this world as it was all screwed up so no timings.. So for me it was not a problem of loaded spawn but more something getting corrupted using version 111 as i always keep spawn loaded
Edit : keep-spawn-loaded-range : 8 , i never changed this value.

**Comment by finlaysawyer** [comment]
Hey, thanks for your replies. I've tried the above, but `keep-spawn-loaded` doesn't really seem to affect it for me. I've fully regenerated my paper.yml and ensured it is set to false. I've tried an old world and a fresh 115 generated world and this also doesn't work.

Edit: Similarly to supertakeru, some squids and phantoms move for me also, but everything else is frozen.

**Comment by ghost** [comment]
Looks like you need to have keep-spawn-loaded-range set to 10. One of my test servers had 7 and the other 8, setting that value to 10 on both of them fixed passive mob ai for me. And it only seems to be working with paper-115.

**Comment by bayi** [comment]
Can confirm:
Version: paper-115 ( tried 112, 113, 114 also )
Loaded plugins: dynmap ( tried without it also )
World was generated originally in 1.14.0

 - No sheeps, cows, horses were moving just spinning around in my base ( at spawn ) or anywere else
 - My creeper farm broke because creepers werent moving away from cats.
 - Interestingly villagers seemed to move ( my farmers were harvesting and dropping the harvested stuff )

 - Settings `keep-spawn-loaded-range` to `10` solved all the above ( had `keep-spawn-loaded` already on `true` )

**Comment by BillyGalbreath** [comment]
~~Can confirm. `keep-spawn-loaded-range` with low values is the cause.~~

~~This was difficult to replicate. I had to tp faaar away from spawn, and i have to use really low values (tested 0 and 1 where mobs wont move. values 8, 9 and 10 mobs moved for me).~~

~~Mobs near spawn always moved for me.~~

~~I'll examine the code now to see what's up.~~

Retracting this. I am able to reproduce mobs not moving even with the above conditions set. Having a hard time tracking this one down.

**Comment by EliasLahham** [comment]
I'm currently on paper build 114 with keep-spawn-loaded-range on 10, but my mobs still won't move.

**Comment by ghost** [comment]
As I mentioned above, it only will work on 115

**Comment by Spottedleaf** [comment]
My test server runs
`keep-spawn-loaded: true`
`keep-spawn-loaded-range: 10`

and I've produced this issue consistently

It's not likely loaded range has anything to do with this.

**Comment by animeavi** [comment]
I noticed fish weren't swimming away but now that I've seen this I also see none of the farm animals are moving other than spinning around in place, both the ones I have in fences and the ones that spawn in the wild. Yesterday I tamed a cat and it followed me for little bit but then wouldn't follow me at all after that, may be related to this bug.

Setting `keep-spawn-loaded-range` to `10` made no difference for me in that regard.

**Comment by ghost** [comment]
What version of paper are you using?

**Comment by animeavi** [comment]
Latest (115)

Also I should add that even if I hit the passive mobs they just stand in place after being hit too.

Just built regular Spigot `git-Spigot-595711b-e8b39d4 (MC: 1.14.3)` and the issue is not present.
It's is definitely an issue on Paper's side.

**Comment by danny6167** [comment]
Just installed a fresh build 115 and having the same issue. No mobs seem to move unless they are hostile mobs that have aggro.

No plugins or config changes.
Timings report: https://timings.aikar.co/?id=7b3a8ca4ccba49818c664f0fb78e42fd

**Comment by theteej** [comment]
Can confirm, on 115 with spawn loaded and a range of 10, mobs still not moving.

**Comment by dvnger** [comment]
on my tests a world generated originally in 1.13, upgraded to 1.13.2 and in production now on 1.14.3 paper-115 the passive mobs work as intended.

with the same configuration files employed across different servers, only the ones with worlds generated in 1.14 are having this issue 

[video link](https://ahegao.ca/u/capture-3.mp4) showing first the world generated in 1.13, then one generated on 1.14

**Comment by Mytchall** [comment]
> on my tests a world generated originally in 1.13, upgraded to 1.13.2 and in production now on 1.14.3 paper-115 the passive mobs work as intended.
> 
> with the same configuration files employed across different servers, only the ones with worlds generated in 1.14 are having this issue
> 
> [video link](https://ahegao.ca/u/capture-3.mp4) showing first the world generated in 1.13, then one generated on 1.14

I am running a 1.13.2 map on 1.14.3 and my mobs do not move. I don't think this is related.

**Comment by Blazzike** [comment]
Fairly certain this is now only occurring on the non-main overworld (and possibly nether and end, unsure).

**Comment by Mytchall** [comment]
> Fairly certain this is now only occurring on the non-main overworld (and possibly nether and end, unsure).

Well, I am not quite sure what you mean by this. On my server, there is only one overworld. Though there are others in the folder, there is no way to access them (no multiverse or anything). Do you mean to imply I should rename my world to whatever the default is? 

edit: also, this occurred on a newly generated test server with no other worlds in folder

**Comment by Blazzike** [comment]
You could try that, might break plugins. The default is "world."

**Comment by dvnger** [comment]
> I am running a 1.13.2 map on 1.14.3 and my mobs do not move. I don't think this is related.


both worlds are running identical hardware, both are on openjdk-11 & both are using the exact same bukkit, spigot & paper.yml configurations. 

transplanting my 1.13.2  -> 1.14 world into the machine which has the passive mob issue results in the mobs moving as intended, doing the same with the 1.14 generated world onto the opposite hardware results in passive mobs not moving as they are intended.

I haven't had the opportunity to test anything else, but I will be able to shortly and update this post.

**11:53pm EST edit** changing the server draw distance to 15 from 12 on the 1.14 paper-115 world and invoking -eraseCache in the startup options resulted in the mobs moving until more than 100 chunks were loaded, then they stopped entirely again

**12:20pm EST edit** by setting tick-inactive-villagers: true to false once the 100 chunk threshold is reached entities no longer stop in place

**Comment by BillyGalbreath** [comment]
My server's world name is `world` and is affected. So, it can't be that.

> Fairly certain this is now only occurring on the non-main overworld (and possibly nether and end, unsure).

**Comment by Mytchall** [comment]
> > I am running a 1.13.2 map on 1.14.3 and my mobs do not move. I don't think this is related.
> 
> both worlds are running identical hardware, both are on openjdk-11 & both are using the exact same bukkit, spigot & paper.yml configurations.
> 
> transplanting my 1.13.2 -> 1.14 world into the machine which has the passive mob issue results in the mobs moving as intended, doing the same with the 1.14 generated world onto the opposite hardware results in passive mobs not moving as they are intended.
> 
> I haven't had the opportunity to test anything else, but I will be able to shortly and update this post.

Well, you may be right. While my world was generated in 1.13.2, we have lots of 1.14.3 blocks and entities on it, which may be the cause.

**Comment by BillyGalbreath** [comment]
Ok. I've pinpointed the issue, ~~but it doesnt make any sense. Holding off on pushing a PR until I understand _why_ this is happening...~~

~~Long story short, commenting out [this line in this paper optimization](https://github.com/PaperMC/Paper/blob/ver/1.14/Spigot-Server-Patches/0307-Prevent-Mob-AI-Rules-from-Loading-Chunks.patch#L63) fixes all issues regardless of settings used previously mentioned in this ticket.~~

Figured it out. Patch is using the wrong `blockposition` variable. Pushing PR to fix this soon.

Edit: To explain why the keep-spawn-loaded range seemed to work was the wrong `blockposition` being used was a relative position to the entity trying to move. Most of the time the entity wanted to move within 10 blocks of where it was at so it was checking if that chunk was loaded (treating the relative coords as absolute coords). More often than not the chunk being checked was 0,0 after doing the block-to-chunk conversion. If your spawn was close to 0,0 and you had a high enough keep-spawn-loaded-range, then the condition was met and the entity moved. For those with a spawn far away from 0,0 or a low keep-spawn-loaded-range the mobs always stayed motionless.

Enjoy the fix, guys and gals ^_^
