### ISSUE TITLE
Villagers 1.15.2 - Profession & Breeding Issues

### ISSUE THREAD

**Issue by iSkeptical** [PaperMC/Paper#2959]
### What behaviour is expected:
Iron farm producing 400-500 iron per hour.
Villagers gossiping and spawn golems in "fright" mode during the night.
Villagers farming and throwing food to nearby villagers in a 1x1 to breed.
Villagers breeding in a 1x1, both willing, food, and beds nearby.
Villagers working at work stations and refilling their trades.

### What behaviour is observed:
Iron farm produces around 100 iron per hour.
Villagers are not spawning golems during the night, despite being in "fright" mode.
Villagers in the iron farm lose/gain professions constantly, and unable to see workstations in a 1x1 if they are surrounded by their stations.
Villagers don't seem to be making food and throwing to nearby villagers in the farm.
Villagers are not breeding nor sleeping in the villager breeder in the 1x1.
Multiple villagers seem to be claiming the same workstation, causing villagers to not be able to refill trades.

### Steps/models to reproduce:
Iron Farm:
https://www.youtube.com/watch?v=CUalWquiOPc

Villager Breeder:
https://www.youtube.com/watch?v=VTseLpa9Iyc

As for the trading hall, placing beds/workstations with villagers seems to replicate that issue.

### Plugin list:
 CoreProtect, LuckPerms, OreAnnouncer, DiscordSRV, Chunkmaster, dynmap, WorldBorder

### Paper build number:
This server is running Paper version git-Paper-103 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

### Anything else:
It's just weird.
I switched to vanilla and craftbukkit with the same world and to me that villagers and the iron golem farm are working fine. I've only seen issues persist when switching back to spigot/paper.

Additional notes:
The farms are built large distances from each other, I've made sure to not punch any villagers, made sure their inventories where empty before tossing them into the farm, and that there are no other work stations nearby the trading halls or

**Comment by imDaniX** [comment]
Is "tick-inactive-villagers" setting enabled in spigot.yml?

**Comment by iSkeptical** [comment]
> Is "tick-inactive-villagers" setting enabled in spigot.yml?

Yes

**Comment by johnneijzen** [comment]
I have a similar problem on my server. 

Paper build number paper-118 with plugins CoreProtect, Chunkmaster, BlockLocker and AuthMeReloaded, and GriefPervention

**Comment by johnneijzen** [comment]
I did find a spigot issue about same problem https://hub.spigotmc.org/jira/browse/SPIGOT-5570

**Comment by johnneijzen** [comment]
Hmm weird all villager died since they could not breed than when I spawn them in manually with villager egg then suddenly starting breeding as normal hmm does it to do have natural with spawn villagers?

**Comment by johnneijzen** [comment]
I just notice multiple village claiming same workstation i have 5 farmer even when are 4 composer
![2020-02-28_05 58 13](https://user-images.githubusercontent.com/1343960/75490627-7698c280-59ef-11ea-8ae9-de463fd90d76.png)
and i did update my server to paper-121
but starting wonder is if it same issue as #2990 i guess i have to run spigot server and see if same problem will happen or not

**Comment by atyshka** [comment]
Would like to chime in and mention bed-claiming as an issue. Built the gnembon iron farm and 2 cells are consistently broken because villagers are failing to claim the middle bed. Design works fine in vanilla and in other 2 cells.

**Comment by ghost** [comment]
Same problem here, 2 unemployed villagers, loads of beds, you throw lots of potatoes, hearts appear but then it stops and one of them throws those angry thunder clouds...
I really hope this gets fixed or someone finds a solution, as players on my server currently aren't able to make villager halls and iron farms

**Comment by aikar** [comment]
Something must be off with the setup:
![Village](https://i.imgur.com/TCWNfUm.png)

I just made villagers create a baby on latest paper. 

If you have any mob limiting plugins or farm limiting plugins, its possible they are cancelling the breed event...

**Comment by EimisM** [comment]
Villagers mechanics needs to be set back to vanilla, villagers dying out even with iron golems protecting them. Also iron golem farms are not working, either iron golems are not spawning or either villagers wake up on the golem spawn platforms. Villager trading systems is also not working. @aikar

**Comment by Proximyst** [comment]
gnembon's iron farm works great on Paper with marginal modifications (which shouldn't even be necessary anymore, I believe) to make the villagers end up in the correct spot:

![https://owo.whats-th.is/63KPx3e.png](https://owo.whats-th.is/63KPx3e.png)

(Yes, I'm aware my version is outdated, but it hasn't been a problem for me on my private server, nor the public one I work for)
I used Docm77's farm before this, and it too worked just fine.

Trades work correctly with discounts:

![https://uwu.whats-th.is/8zSmV7p.png](https://uwu.whats-th.is/8zSmV7p.png)

And they breed fine with the "de-facto standard" breeder:

![https://owo.whats-th.is/57fKmyh.png](https://owo.whats-th.is/57fKmyh.png)

Check your configurations and plugins, because they all work great with the following:

![https://owo.whats-th.is/6BGDSrg.png](https://owo.whats-th.is/6BGDSrg.png)

**Comment by EimisM** [comment]
It might work great with few designs and plugins. Although I want to stay as close to vanilla. No plugins and all designs from youtube working. Wouldn't it be better for the most of us to implement vanilla villager logic back into paper, since it doesn't provide any performance increase?

Also design that you are using @Proximyst  iron golems is not spawned every time. With this logic you have to block their view from time to time. Extremely inefficient

**Comment by Aurelien30000** [comment]
Hey !

I can confirm, villagers' behaviour was strongly affected by all the changes in paper, and this situation causes issues with iron farms productivity, villagers' activity (farmers have troubles to recolt crops sometimes), etc :/
By my own tries, villagers were almost like in vanilla before build 150, something like that, I don't really know sadly, and I could be sure the cause is paper, nothing changed except paper...
Despite useful optimisations to improve performances (and it's necessary to welcome players with these recent versions), "we" would be grateful if you could revert a bit or make villagers "better", with a behaviour close to vanilla's, because gameplay is too influenced now.

Thanks ! :)

**Comment by Marcelo-Petrucelli** [comment]
Well, from my observations, I can almost certainly confirm two things about this issue:

1. This seems to be when the chunck unloads (or loads back). - Check Note 1
2. This also seems to mess villagers beds, sleeping and working periods. - Check Note 2

Note 1: I have an iron farm pretty close to my base. But my server view-distance is always set to 8. Unfortunately, I can't always keep a distance of less then 8 chucks from my base all the time (since it's a bit big). When I load it back to farm iron, I usually have to reset the farm (taking the zombie from the sight of the villagers for a period OR letting them sleep and work a bit, usually for one or 2 days cycle). After that, they seem to go back to spawning golems, but not correctly or at the same time.

Note 2: My villager farms (farming villagers) actually got messy as well, since villagers seems to be changing beds when their chuck is reloaded. They seem to simply choose another bed and also another working station. I also observed 2 villagers taking the same working station or, in some way, keeping the old workstation while a new villager picks it as well.

One possible suggestion is to use Fabric's Carpet Mod and check it. I'll look into it.

**Comment by aikar** [comment]
My players told me that farms are working now, what are your spigot settings

**Comment by EimisM** [comment]
They are completely defaul. As soon as I change .jar to craftbukkit or spigot, everything works fine. When I switch it back to paper same issues happens again. Even tried to update paper.jar same stuff. 

Could you just please listen to us and bring back the good Villagers (vanilla) behavior @aikar ?

**Comment by aikar** [comment]
If you want pure vanilla behavior of villagers, set spigot.yml entity-activation-range section villagers to 0.

If that still doesn't work, then we can see what's wrong.

**Comment by aikar** [comment]
Build 231 should now also help by restoring vanilla behavior of beds for Villagers.

**Comment by Marcelo-Petrucelli** [comment]
Yep, everything seems to be back to normal.

**Comment by hennedo** [comment]
The issue where multiple Villagers are using one workstation still seems to exist in Build 284

**Comment by Marcelo-Petrucelli** [comment]
That's strange @henne- I had no more problems with this. Still using 237 though.

**Comment by hennedo** [comment]
I have a Villager Trading hall, with about 7 Villagers, they all use their workstation and refresh their trades. They all cannot move away from their workstation. When I put a new Villager with no profession next to them, it takes some time but at some point he chooses a random workstation and turns into e.g. a Librarian. That happens while the villager behind the Lectern still uses it...

**Comment by Vesek** [comment]
@henne- i have same issue with my trading hall, i fixed it by blocking access to other workstations while adding a new one.
![image](https://user-images.githubusercontent.com/61123478/82494668-3a569900-9aea-11ea-97e1-f50df66cc04e.png) Paper version 304.

**Comment by bradam12** [comment]
I have a free roaming village, one composter, and one farmer (master). Several villagers with no jobs. If I leave the chunk and come back, sometimes one of the villagers will also take up farming, so two farmers for one composter.
I teleported the villagers away and trapped them to let the farmers reset back to one, but once I left the chunk and came back, a second farmer was there.  Was running 284, but rolled back to 231 and can replicate there as well. Also removed and replaced the composter each time.

I also observed this with other professions, but most commonly with farming.

**Comment by hennedo** [comment]
Mh.. If I understand this correctly, it seems to be a bug from the original server. It is fixed in the current 1.16 snapshot https://bugs.mojang.com/browse/MC-150806

Edit:
Currently AFKing in my affected world on a vanilla server to confirm wether this bug happens even in the vanilla server.
If I understand it correctly, paper based on Spigot? Because I tried using spigot to get rid of this bug, but it is apparently also affecting CraftBukkit git-Spigot-800b93f-8160e29

**Comment by aikar** [comment]
Can someone tell me if this is happening anymore on 325+?

Apparently our async chunks had a risk of POI data not saving, and if that happened, there was risk of the fact the POI was claimed being lost.

But Leaf fixed that supposively, and we also have other optimizations to Villagers pathfinding that lets them favor their local workstation more.

This might now be resolved.

**Comment by juliowh** [comment]
I am playing at 327 and the bug still happens, looks like that it stopped breeding after making some villagers claim some workstations. I traded with them and now even if I remove all the workstations and let only the farmer one it doesn`t come back to work.

**Comment by aikar** [comment]
You may need to adjust your Entity Activation Range settings to help with that.

At this time, I don't believe there is anything left to do here because I can not reproduce any issues with Villagers. They are working as designed when activated, and mojang has improved the behavior in 1.16 saying something was wrong with 1.15.2, however the code does look fine.

So going to say whatever is still occurring is just how it's going to be until 1.16 unless someone can identify ways to improve.

Latest does have some immunity boosts, but if your villagers are out of activation range, then yes they can miss working and breeding windows...

There is inactive wake up settings, you can tweak them to wake up more often. But your going to have to choose between villager default behavior and performance some here.

**Comment by bradam12** [comment]
> You may need to adjust your Entity Activation Range settings to help with that.

Is that setting villagers to 0? Or are there other recommendations?

**Comment by aikar** [comment]
shouldn't need zero... but could increase range or ensure inactive villagers config isn't 0 which someone might have suggested for performance reasons.

Or optionally use the setting "tick inactive villagers"

**Comment by mythiccals** [comment]
> shouldn't need zero... but could increase range or ensure inactive villagers config isn't 0 which someone might have suggested for performance reasons.
> 
> Or optionally use the setting "tick inactive villagers"

can you suggest a setting to turn it to? I'm stuck in finding a number that resolves the issue but doesn't kill performance.

**Comment by Tomigames** [comment]
Any updates on ^^?
