### ISSUE TITLE
ItemFrame interactions are broken after teleport

### ISSUE THREAD

**Issue by Fejm** [PaperMC/Paper#3174]
### What behaviour is expected:
Interact with Item Frames as normal

### What behaviour is observed:
After teleport interactions are broken (tested on ItemFrames)
https://youtu.be/JsnOuzSXwxU (uploading)

### Steps/models to reproduce:
1. Place some Item Frames
2. Teleport to other location for some time
3. Teleport to Item Frames
4. Try to interact

### Plugin list:
none

### Paper build number:
[08:23:15 INFO]: This server is running Paper version git-Paper-"0a4286c" (MC: 1.15.2) (Implementin
g API version 1.15.2-R0.1-SNAPSHOT)

### Anything else:
___Anything else you think may help us resolve the problem___

**Comment by Fejm** [comment]
Players report that block breaking is also aftected

**Comment by Fejm** [comment]
Sometimes you are unable to break blocks too.

**Comment by Aurelien30000** [comment]
You should try with a public build of Paper before, because your server seems running a custom version built ^^
Does this issue occur on Spigot or Vanilla, check also, just in case 🤔

**Comment by Fejm** [comment]
Yes, I built it from the source manually. Latest commit as you can see.
Only occur on Paper. Older build (979b53a) works fine.

**Comment by aikar** [comment]
Your going to need to provide more than this. Errors thrown, reproduce steps on a fresh server w/ latest build, etc.

I'm running it in production and not having any issues.

The only recent change relevant here is https://github.com/PaperMC/Paper/commit/59453f66754cfe10b9f819a1d715a4e8d10ac208

Can you try before and on that build?
Do you have plugins doing anything special with cancellation of interact?

Only other thing I can see if is your players considered dead by server. Getting any cannot send chat message errors?

**Comment by Fejm** [comment]
> Your going to need to provide more than this. Errors thrown, reproduce steps on a fresh server w/ latest build, etc.

No errors. Video has been made on fresh server, builded from source 0a4286c

If you reconnect to server then you are able to interact with things until next teleport.
Also i confirmed that latest build has issues with block breaking. It's looks like the same case with item frames but it's harder to reproduce.

> Do you have plugins doing anything special with cancellation of interact?

0 plugins on test server (video)

> Only other thing I can see if is your players considered dead by server. Getting any cannot send chat message errors?

No. Chat works fine.

Sometimes you are able to teleport and everything works, sometimes not.

Well, i was able to reproduce issue with frames on "stable" 979b53a , block breaking works fine. 100 players playing on this right now at noone reported issue. After updating to 0a4286c players start complaining about almost everything.

**Comment by aikar** [comment]
Do you have any data packs? We totally just spent a ton of time debugging someones issue with "0 plugins" to find it was a datapack....

**Comment by Fejm** [comment]
I just created new directory, put paper.jar / eula.txt and start recording. Complete fresh server, maps, configs etc.

**Comment by aikar** [comment]
Build 193 is building now should fix this.

**Comment by Fejm** [comment]
It's still broken but somehow harder to reproduce (tried 3 times).

https://youtu.be/WnzXNopZ2T8

Just wait for boat example. Client still "see" ghost entity?

**Comment by Spottedleaf** [comment]
Are you able to make chat messages when the entity interaction fails?

**Comment by Fejm** [comment]
Yes

**Comment by Brokkonaut** [comment]
I can confirm this issue on my server, Paper 193. This did not happen in Build 137 (yes I know its a huge span, we did not update for a while).

I have not found a reliable way to reproduce it but a lot of players reported uninteractable item frames. Teleporting away and back or relogging often fixes the problem for a while.

I do not think it is caused by a plugin, because it worked before and I did not update any plugins since then, but here is the list:
Plugins (65): AddEveryoneToScoreboardTeam, AdditionalWorldeditBrushes, ArmorStandTools, BCalculator, BirthdayGhosts, bPermissions, BrokkoCommandLogger, BrokkoSecurity, BungeeNCPNotify, CashMachine, ChestShop, ChestShopAddons, CityBuilder2, CityBuilderPlotWorldGenerator, CreativeEntities, CubeCompanion, CubeConomy, CubeQuest, CubeShop, CubesideAdvancedEquipment, CubesideEventplan, CubesideSettings, CubesideStatistics, CubesideVoteManager, dynmap*, Essentials, FakePlotMe, GamesInWorlds, GlobalAutoMessage, GlobalChat, GlobalClient, GlobalPort, HalloweenGhosts, Head-Cases, InteractiveBookAPI, LogBlock, LWC, Multiverse-Core, MyHelpPages, NoCheatPlus, NoteBlockAPI, OpenInv, PistonBlocker*, PlayerStatistics, PlayerUUIDCache, ProperTime*, ProtocolLib, ProtocolSupport, ProtocolSupportAddons, ProtocolSupportVersions, RedstoneMechanics, SecurityTool, SimpleTrading, SpawnSpiele, SuperElytra, TCGGiver, TeamspeakBridge*, TreasureChest, VanishNoPacket, Vault, WESV, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags
