### ISSUE TITLE
Crash on startup.

### ISSUE THREAD

**Issue by SKevo18** [PaperMC/Paper#3209]
So, after looking on the internet for a while, I'm unable to fix my problem. After updating from `paper-162 MC: 1.15.2`, my server crashes every time I start it up. I don't know what the problem is.

Judging from where the stack trace appears (it appears always around dynmap and BentoBox plugins), I tried disabling these plugins. But that didn't fix my issue. I'm also 99% sure it's not plugin issue as `paper-162` works without any issues with same plugins and with same plugin versions. Another reason why I think it's a Paper issue (perhaps the recent chunk changes, not sure) is that the issue occurs even when disabling all the plugins.

Here is how the logs look when there are absolutely no plugins enabled:
https://mclo.gs/X3kYx0z (https://pastebin.com/0ystgrr0)

I'd appreciate any help, as I'm hopeless and I have no idea if this is a plugin or Paper bug.

### Link/paste of stack trace
My entire logs with all plugins enabled:
https://mclo.gs/7MJUsSZ (https://pastebin.com/dL55Px7y)

___We need all of the stack trace! Do not cut off parts of it. Please do not use attachments. Upload your logs to a paste site or paste directly here.___

___Please do not make reports when the report says "DO NOT REPORT THIS TO PAPER". These are simply messages informing you of lag, to find what is causing it. Ask for tips on Discord or IRC instead.___

### Plugin list:

```AdvancedBan-2.1.8-RELEASE.jar	
 
AnimatedFrames_v4.11.5-SNAPSHOT.jar	
 
ArtMap-3.3.8.jar	
 
AsyncWorldEdit-3.6.20.jar	
 
AuctionHouse-2.0.8.jar	
 
BKA.jar	
 
BannerMaker.jar	
 
BarAPI.jar	
 
BedWars-0.2.6.jar	
 
BookNotification-0.1.7.jar	
 
CMI8.6.22.2.jar	
 
CharsApi.jar	
 
Citizens-2.0.26-b1868.jar	
 
CitizensCMD.jar	
 
CitizensText.jar	
 
Command Panels v2.8.0.jar	
 
CompatNoCheatPlus (MCMMO Support For NCP).jar	
 
ConditionalCommands.jar	
 
ConsoleSpamFix-1.8.2.jar	
 
CoreProtect-2.18.2.jar	
 
CrackShot.jar	
 
Crawling.jar	
 
CrazyCrates.v1.10.jar	
 
CustomStructures.jar	
 
DefensiveTurrets.jar	
 
DiscordSRV-Build-1.18.4.jar	
 
Dynmap-3.0-beta-10-spigot.jar	
 
EasyEmojis-3.0.jar	
 
GriefPrevention.jar	
 
HackedCore.jar	
 
HackedServer-2.51.0.jar	
 
HeadDatabase.jar	
 
IllegalStack.jar	
 
InteractionVisualizer-1.10.4.jar	
 
InventoryRollback-2.0-beta.jar	
 
ItemEdit.jar	
 
LightAPI-fork-3.4.2.jar	
 
LuckPerms-Bukkit-5.0.72.jar	
 
MapManager_v1.7.8-SNAPSHOT.jar	
 
MineChess.jar	
 
Minigames-1.15-SNAPSHOT.jar	
 
Minigames-Regions-1.15-SNAPSHOT.jar	
 
Multiverse-Core-4.1.1-SNAPSHOT.jar	
 
Multiverse-NetherPortals-4.1.0.jar	
 
MyPet-3.10.jar	
 
MythicMobs-4.9.0.jar	
 
NoCheatPlus.jar	
 
NoteBlockAPI-1.4.5-SNAPSHOT.jar	
 
PacketListenerAPI_v3.7.6-SNAPSHOT.jar	
 
PlaceholderAPI-2.10.5.jar	
 
Plan-5.1-build-505.jar	
 
PlayerParticles_v7.9.jar	
 
PlayerVaultsX.jar	
 
PlayerWarps 5.0.9.jar	
 
PlugMan.jar	
 
PocketGames.jar	
 
PremiumVanish.jar	
 
ProtocolLib.jar	
 
QuickShop-4.0.2.2.jar	
 
SelectionVisualizer-3.0.0.6.jar	
 
ServerListPlus-3.5.0-SNAPSHOT-Universal.jar	
 
ServerTutorialPlus-1.21.3-SNAPSHOT.jar	
 
Shopkeepers-2.9.2.jar	
 
Skript.jar	
 
SystemInfo-1.0.12.jar	
 
TigerReports.jar	
 
TreasureChestReloaded.jar	
 
TwitchSync-1.4.2.jar	
 
Vault1.6.11.jar	
 
VoidGenerator-1.5.6.jar	
 
VotifierPlus.jar	
 
VotingPlugin.jar	
 
WDLCompanion-1.2.0.jar	
 
WorldBorderPlugin-1.152.1-SNAPSHOT.jar	
 
WorldChangeScreenRemover.jar	
 
WorldGuardExtraFlags.jar	
 
bentobox-1.12.0.jar	
 
buildbattle-4.3.2.jar	
 
customcrafting-1.5.4.0.jar	
 
perworldinventory-kt-2.3.2.jar	
 
potionextender-22.jar	
 
racing-1.27.0.jar	
 
wolfyutilities-1.5.6.13.jar	
 
worldedit-bukkit-7.1.0.jar	
 
worldguard-bukkit-7.0.2.jar
```

### Actions to reproduce (if known):
Start the server.

### Paper build number:
I cannot run /version, since the server crashes on startup, but I'm using `paper-209 MC: 1.15.2`

**Comment by aikar** [comment]
should be fixed in newest now. Do you have the watchdog settings changed to turn off early warning or anything?

**Comment by SKevo18** [comment]
Hello, thank you for quick reply & I appreciate that, unfortunately, when I use the latest build (paper-211), I'm still getting this error: https://mclo.gs/9WrQh7a

I haven't changed Watchdog settings, my paper.yml contains this:
```
watchdog:
    early-warning-every: 5000
    early-warning-delay: 10000
```

**Comment by arts7493** [comment]
same error
so i'm using paper 205

**Comment by aikar** [comment]
@xCustomWorld can you still reproduce anymore without plugins? What is your spigot.yml watchdog settings?

@arts7493 are you saying 205 is not affecting you or that its what you are using

**Comment by SKevo18** [comment]
Pretty much same error happening: https://mclo.gs/CMgOmhL

My `spigot.yml`:
```
# This is the main configuration file for Spigot.
# As you can see, there's tons to configure. Some options may impact gameplay, so use
# with caution, and make sure you know what each option does before configuring.
# For a reference for any variable inside this file, check out the Spigot wiki at
# http://www.spigotmc.org/wiki/spigot-configuration/
# 
# If you need help with the configuration or have any questions related to Spigot,
# join us at the IRC or drop by our forums and leave a post.
# 
# IRC: #spigot @ irc.spi.gt ( http://www.spigotmc.org/pages/irc/ )
# Forums: http://www.spigotmc.org/

config-version: 12
settings:
  log-villager-deaths: true
  save-user-cache-on-stop-only: false
  sample-count: 12
  bungeecord: false
  player-shuffle: 0
  user-cache-size: 1000
  moved-wrongly-threshold: 0.1
  moved-too-quickly-multiplier: 10.0
  timeout-time: -1
  restart-on-crash: false
  restart-script: ./start.sh
  netty-threads: 4
  debug: false
  attribute:
    maxHealth:
      max: 2048.0
    movementSpeed:
      max: 2048.0
    attackDamage:
      max: 2048.0
messages:
  whitelist: You are not whitelisted on this server!
  unknown-command: §8███████\n§8███§c█§8███\n§8███§c█§8███\n§8███§c█§8███ §r §r §r
    §r §r §r §r §r §r §r §r §r §r §r §r §r §r §r §r §r §r §r §r §r §r §c§lError\n§8███§c█§8███
    §r §r §r §r §r §r §r §r §r §r §r §r §r §6This command does not exist.\n§8███████
    §r §r §r §r §r §r §r §r §r §r §r §r §r §r §r §r §r §r §eType §6/help §efor help.\n§8███§c█§8███\n§8███████
  server-full: The server is full!
  outdated-client: Outdated client! Please use {0}
  outdated-server: Outdated server! I'm still on {0}
  restart: Server is restarting
commands:
  log: true
  tab-complete: 0
  send-namespaced: true
  spam-exclusions:
  - /skill
  - /gd:callback
  silent-commandblock-console: true
  replace-commands:
  - setblock
  - summon
  - testforblock
  - tellraw
advancements:
  disable-saving: false
  disabled:
  - minecraft:story/disabled
stats:
  disable-saving: false
  forced-stats: {}
world-settings:
  default:
    seed-endcity: 10387313
    trident-despawn-rate: 1200
    verbose: true
    mob-spawn-range: 8
    hopper-amount: 1
    dragon-death-sound-radius: 0
    seed-village: 10387312
    seed-desert: 14357617
    seed-igloo: 14357618
    seed-jungle: 14357619
    seed-swamp: 14357620
    seed-monument: 10387313
    seed-shipwreck: 165745295
    seed-ocean: 14357621
    seed-outpost: 165745296
    seed-slime: 987234911
    max-tnt-per-tick: 100
    view-distance: default
    enable-zombie-pigmen-portal-spawns: true
    item-despawn-rate: 6000
    arrow-despawn-rate: 1200
    wither-spawn-sound-radius: 0
    hanging-tick-frequency: 100
    zombie-aggressive-towards-villager: true
    nerf-spawner-mobs: false
    max-entity-collisions: 8
    merge-radius:
      exp: 3.0
      item: 2.5
    growth:
      cactus-modifier: 100
      cane-modifier: 100
      melon-modifier: 100
      mushroom-modifier: 100
      pumpkin-modifier: 100
      sapling-modifier: 100
      beetroot-modifier: 100
      carrot-modifier: 100
      potato-modifier: 100
      wheat-modifier: 100
      netherwart-modifier: 100
      vine-modifier: 100
      cocoa-modifier: 100
      bamboo-modifier: 100
      sweetberry-modifier: 100
      kelp-modifier: 100
    entity-activation-range:
      water: 16
      animals: 32
      monsters: 32
      raiders: 48
      misc: 16
      tick-inactive-villagers: true
    entity-tracking-range:
      players: 48
      animals: 48
      monsters: 48
      misc: 32
      other: 64
    ticks-per:
      hopper-transfer: 8
      hopper-check: 1
    hunger:
      jump-walk-exhaustion: 0.05
      jump-sprint-exhaustion: 0.2
      combat-exhaustion: 0.1
      regen-exhaustion: 6.0
      swim-multiplier: 0.01
      sprint-multiplier: 0.1
      other-multiplier: 0.0
    max-tick-time:
      tile: 50
      entity: 50
    squid-spawn-range:
      min: 45.0
  worldeditregentempworld:
    verbose: false
```

**Comment by aikar** [comment]
timeout-time: -1

Seems to be the cause here.

I will fix this on our side, but if you want the server to work, set this back to 60 or higher.

**Comment by aikar** [comment]
Did you just change this config? from what i can see, -1 has never been supported.

**Comment by SKevo18** [comment]
I adjusted the config for my needs a long time ago, haven't edited since then. `-1` always worked fine for me, have you changed something? Today, I can try the default version though.

**Comment by aikar** [comment]
-1 is not a legal value. it couldn't have worked.
I just tested it on spigot, instant crash. 
Tested it on paper w/o my recent changes, instant crash.

That is why you're crashing. I'm gonna put in a patch to auto fix <= 0 to be 5 minutes, but there was one more ThreadDeath thankfully your logs showed me to fix.

**Comment by SKevo18** [comment]
Oh, strange. When I used `-1` before `paper-162`, it treated `-1` as infinite and worked fine. Perhaps spigot changed something recently 🤔

Anyways, I can confirm that the issue is `timeout-time` in `spigot.yml`. Setting it to `300` (5 minutes) solved the issue. When it was `-1`, server then stopped instantly when there was even a little lag from loading a plugin, for example. 

Thank you very much for your help and quick assistance, I really appreciate that!

**Comment by aikar** [comment]
i cant explain how it could of worked, because -1 is -1 seconds, meaning "if server hasn't ticked in -1 seconds, crash"

well that scenario will always be true. I checked spigots code, and every change we've made. -1 has never been supported.

I 100% reverted all recent changes, still crash.

**Comment by SKevo18** [comment]
Well, server thinks that -1 seconds already passed, because the check is `if server is not responding for (more than?) -1 second` - there is always more than -1 second, so it shuts down immediately.

To be honest, I don't really care how this thing worked before for me and possibly for @arts7493 too, I'm just glad I solved the issue 🤷‍♀️
