### ISSUE TITLE
[1.16] Old serialized heads (from 1.15 or before) do not load in 1.16.1

### ISSUE THREAD

**Issue by Brokkonaut** [PaperMC/Paper#3734]
### What behaviour is expected:
When loading the head from a yaml it should have a skin (it worked in all versions up to 1.15.2)

### What behaviour is observed:
It has no skin in 1.16.1

### Steps/models to reproduce:
Load the head in a plugin and give it to a player

### Plugin list:
n/a

### Paper build number:
 This server is running Paper version git-Paper-29 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

### Anything else:
This is the serialized yaml. https://pastebin.com/Ce7LqL1n

**Comment by UltraFaceguy** [comment]
Same issue here, the 'internal' field is not serialized/deserialized

**Comment by aikar** [comment]
should be fixed in build 30

**Comment by Brokkonaut** [comment]
No, it is not fixed. Loading that yaml still gives me a head without a texture in 1.16.1.

This server is running Paper version git-Paper-34 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

**Comment by UltraFaceguy** [comment]
Also still not working for me, the 'internal' field is still stripped from the metadata
version git-Paper-33 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

**Comment by aikar** [comment]
Ok I see issue, game profiles have a third format of just string. will fix today.

**Comment by ghost** [comment]
on paper 34 and issue is not fixed https://imgur.com/a/O0xK678

**Comment by ghost** [comment]
my bad aikar, didnt see your comment.

**Comment by aikar** [comment]
Should be good now on latest

**Comment by Brokkonaut** [comment]
thanks, it is working now
