### ISSUE TITLE
Raids don't trigger

### ISSUE THREAD

**Issue by beckadamtheinventor** [PaperMC/Paper#3941]
### What behaviour is expected:
Raids should always trigger when player has bad omen effect, and is within range of a proper village.
A proper village includes at least one villager, a bed, and a job station.

### What behaviour is observed:
Raid triggers inconsistently or not at all.

### Steps/models to reproduce:
This raid farm works sometimes but not always.
https://www.youtube.com/watch?v=TDnppbTrdks&t=442s

### Plugin list:
Unfortunately server admins neglected to share this information.
All I know is this worked fine on bukkit. No plugin changes since the switch.

### Paper build number:
git-Paper-321 (MC 1.15.2)

### Anything else:
Villager doesn't always appear to have AI.

**Comment by MrIvanPlays** [comment]
What are your EAR and ETR settings?

**Comment by beckadamtheinventor** [comment]
ETR
    entity-tracking-range:
      players: 48
      animals: 48
      monsters: 48
      misc: 32
      other: 64
EAR
    entity-activation-range:
      raiders: 48
      water: 16
      villagers: 32
      flying-monsters: 32
      villagers-work-immunity-after: 100
      villagers-work-immunity-for: 20
      villagers-active-for-panic: true
      animals: 30
      monsters: 30
      misc: 14
      tick-inactive-villagers: false

**Comment by MrIvanPlays** [comment]
try increasing the ear for raiders and see what will happen.

**Comment by Proximyst** [comment]
Cannot reproduce on 1.16.2.

**Comment by beckadamtheinventor** [comment]
On that note, I assume the issue is resolved in 1.16.2.

**Comment by DeTOB04** [comment]
I am still having this problem getting this exact same raid farm to work on 1.16.5

**Comment by Chew** [comment]
If so, please open a new issue, and be sure to fill out the template completely
