### ISSUE TITLE
Server out of memory due to overload of light work

### ISSUE THREAD

**Issue by ElementW** [PaperMC/Paper#4288]
### What behaviour is expected:
The light engine queue should empty itself and its elements be garbage collected as the pending light requests are emitted during normal gameplay.

### What behaviour is observed:
After some time (generally > 24 hours on my low traffic server) the elements stop being GC'd and end up taking a *lot* of memory as shown by the top entries of this heap dump:

 num   | #instances   |     #bytes | class name (module)
-------|--------------|------------|--------------------
   1:  |   66525200   | 2128806400 | net.minecraft.server.v1_16_R2.LightEngineThreaded$LightQueue$$Lambda$4797/0x0000000801512440
   2:  |   66526840   | 1596644160 | java.util.concurrent.ConcurrentLinkedQueue$Node (java.base@11.0.6)
   3:  |     763789   |  204482288 | [B (java.base@11.0.6)
   4:  |     251737   |  146716880 | [J (java.base@11.0.6)
   5:  |     558194   |   65546056 | [Ljava.lang.Object; (java.base@11.0.6)
   6:  |      41282   |   20362208 | [I (java.base@11.0.6)
   7:  |     681347   |   16352328 | java.lang.String (java.base@11.0.6)
   8:  |     492963   |   15774816 | java.util.HashMap$Node (java.base@11.0.6)

Eventually, this triggers a `java.lang.OutOfMemoryError: GC overhead limit exceeded` (Java 11 w/ G1GC) and crashes the server.

### Steps/models to reproduce:
No exact idea on what triggers this behavior. I only know it happens after some amount of time has passed since server startup. May be related to specific plugins somehow.

### Plugin list:
BookNews*, Chair, CoreProtect, CrashStat [1], DecoHeads*, DiscordSRV, DragonEggDrop, dynmap*, Essentials, EssentialsSpawn, FastAsyncWorldEdit (dummy), GriefPrevention, GriefPreventionFlags, ImageOnMap, JDynmapGriefPrevention*, LuckPerms, Multiverse-Core, Multiverse-Inventories, NoCheatPlus, PlaceholderAPI, Plan, PlayerHeads, PlotSquared, PluginManager*, [PolyWrench](https://gitlab.com/thelavendercloset/polywrench), ProtocolLib, Shopkeepers, SilkSpawners, SinglePlayerSleep, spark, TAB, [TelegramChat](https://gitlab.com/thelavendercloset/telegramchat), WorldBorder, WorldEdit, XpBottler

[1]: plugin created to analyze this bug. Periodically performs heap dumps when exceeding a certain heap size threshold.

### Paper version:
 `git-Paper-174 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)`
Also happens on 1.16 Paper 128, 133.
Not thoroughly tested on 125 but seemed to happen less often (before some light optimizations were introduced).
Didn't happen on 1.15 Paper.

### Anything else:
This might be triggered by one or more plugins, although I fail to see which one would trigger that.
Also, it seems light requests are regularly emitted (even with nobody online, possibly due to some piston machinery within the spawn chunks) and as such when the light queue emptying/GC stops causes a steep increase in memory usage, until the aforementioned crash, as seen at the end of this graph:
![Screenshot_2020-09-05_15-03-23](https://user-images.githubusercontent.com/396420/92305592-031cd280-ef89-11ea-8a14-4f6348a02bff.png)

I will also try to observe the per-world light queue sizes over time to determine if it's actually a garbage collection related issue due to stray references, or if the queues themselves stop emptying/fill faster than they empty.

**Comment by PaulBGD** [comment]
Can confirm this exists, I found it on vanilla Paper a few weeks ago. There's a second leak that's very similar I reported to Tuinity that got "fixed" (not merged yet due to other bugs) here: https://github.com/Spottedleaf/Tuinity/commit/200f825f7b51e868cd22ee1f8b0ff58dc206d7a5

**Comment by aikar** [comment]
yeah somethings definitely "wrong" but I don't suspect its a leak, but more so something goes into a logical loop that is bombarding the system with tasks.

chickeneer had this in memory when he ran out of memory:
1.1 GB of ThreadedMailBox
543.8 MB of LightEngineThreaded

with logs of: https://pastebin.com/rF64kAMi
#4308 would be a duplicate of this.

**Comment by chickeneer** [comment]
Made that paste a gist. So it won't expire. https://gist.github.com/chickeneer/544e4d9f76d2d3c1e1c164b7be98233d

**Comment by Govindass** [comment]
I've just observed the same issue after analyzing one server's heap dump, any updates on it?

**Comment by chickeneer** [comment]
> I've just observed the same issue after analyzing one server's heap dump, any updates on it?

No progress yet. My issue is reproducible, so when time allows we will be debugging till we find the actual source.
The specific cause of the queue growing out of control has not yet been identified

**Comment by FarkasJoseph** [comment]
I have also been having this issue, adding more ram only delays the issue, and changing the light queue size didn't seem to help.

**Comment by HexedHero** [comment]
I've had my server up for 4+ days now and this is my LightEngineThreaded heap, only 0.5% with LightQueue being pretty much 0.

```
Class Name                                                                   | Shallow Heap | Retained Heap | Percentage
-------------------------------------------------------------------------------------------------------------------------
net.minecraft.server.v1_16_R2.LightEngineThreaded @ 0x3ce88b9a0              |           56 |    31,485,280 |      0.54%
|- net.minecraft.server.v1_16_R2.LightEngineSky @ 0x3ce8b7390                |           72 |    21,925,336 |      0.38%
|- net.minecraft.server.v1_16_R2.LightEngineBlock @ 0x3ce88b9d8              |           72 |     9,509,712 |      0.16%
|- net.minecraft.server.v1_16_R2.LightEngineThreaded$LightQueue @ 0x3ce918380|           32 |        36,760 |      0.00%
|- java.util.ArrayList @ 0x3ce91fd58                                         |           24 |         9,632 |      0.00%
|- java.util.ArrayList @ 0x3ce91fd70                                         |           24 |         3,608 |      0.00%
|- net.minecraft.server.v1_16_R2.Mailbox$1 @ 0x3ce91fca8                     |           24 |           160 |      0.00%
|- java.util.concurrent.atomic.AtomicBoolean @ 0x3ce91fd48                   |           16 |            16 |      0.00%
-------------------------------------------------------------------------------------------------------------------------
```

**Comment by aikar** [comment]
theres is not a leak in the queue, the issue is more that the queue is bombed with work, something generates a massive amount of work at once as a logical issue, so renaming ticket.

**Comment by FarkasJoseph** [comment]
The only plugins I have in common with ElementW are DiscordSRV, Dynmap, and LuckPerms. My complete plugin list is: AntiCreeper, Chestshop, Craftconomy, DiscordSRV, DriveBackupV2, Dynmap (snapshot 1.16.3 version), floodgate + Geyser, Graves, Harbor, Luck Perms, Lunar Freecam, LWCX, SpawnDelay, Time is Money, Vanilla Tweaks, and Vault.

**Comment by HexedHero** [comment]
You both use Dynmap, maybe that's making the queue have a fuck ton of work.

**Comment by aikar** [comment]
It gets weirder, chickeneer is one of my team members. He gets this issue when joining fresh after the server start, where as I do not in the exact same code base.

**Comment by Bulldozer2138** [comment]
I've observed the same issue with CraftBook's Chunk Anchors to keep certain chunks loaded even when no players are nearby.
For testing purposes I've removed all other plugins, so currently I'm testing Paper 206 with CraftBook, WorldEdit (as dependency of CraftBook) and Spark to debug memory issues.
When I enable a Chunk Anchor and log out, the number of LightEngineThreaded$LightQueue instances increases rapidily. After ~ 50 minutes I already count 16 million instances:
Rank | Instances | Size | Type
-- | -- | -- | --
Total | 37.744.422 | 1.17 GB | n/a
1 | 16.142.716 | 492.64 MB | net.minecraft.server.v1_16_R2.LightEngineThreaded$LightQueue$$Lambda$4137/0x0000000840c0ec40
2 | 16.195.444 | 370.68 MB | java.util.concurrent.ConcurrentLinkedQueue$Node

Interestingly, as soon as sombody logs in again, the number of instances goes down very quickly and stays at a sane level until logout, where it starts to grow again.
Looks like processing of that queue stalls in certain situations?

**Comment by MinecraftCitiesNetwork** [comment]
We're getting the same issue too. Would love a resolution.

**Comment by ElementW** [comment]
Been running the server on Paper 258 for a day, with Dynmap disabled as it isn't yet updated for 1.16.4, same problem. Dynmap still may be making the problem worse but isn't the problem by itself.

**Comment by NotStarRift** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/17240279/100403028-9575c500-3012-11eb-86f7-8cf1721fcd15.png)
Yep, same issue here! It does look like DynMap might be the culprit, so I have disabled it in the meantime. That seems to have really helped out a lot

**Comment by FarkasJoseph** [comment]
Well I haven't had the issue much, but I think it is still there. I had heard purpur has redesigned the lighting system, but waited to see if paper would fix this bug. I waited a while, but it seems like it is here to stay, so I'm going to try purpur for a few days and let you all know how it goes. [https://github.com/pl3xgaming/Purpur](https://github.com/pl3xgaming/Purpur)

**Comment by Govindass** [comment]
> Well I haven't had the issue much, but I think it is still there. I had heard purpur has redesigned the lighting system, but waited to see if paper would fix this bug. I waited a while, but it seems like it is here to stay, so I'm going to try purpur for a few days and let you all know how it goes. [https://github.com/pl3xgaming/Purpur](https://github.com/pl3xgaming/Purpur)

Purpur has the same issue last time I checked

**Comment by tackleza** [comment]
I have same problem. Something is wrong with LightEngineThreaded. Only happened when 0 player online. That weird!

(I think) problem is when "redstone" turn on-off water and water flow? and need to recalculate lighting?
For example mob farm that flush mob by water. Which that farm is always on
![image](https://user-images.githubusercontent.com/3255203/113262520-e700ca00-92fa-11eb-9695-2cddc14d6896.png)
(This need to be in spawn chunk. But far from spawn point, from images number 31-32)
(Need more testing!)

Here some heap file: https://drive.google.com/file/d/13kHdDbU6JyHerDJF24K0Bl3CBVNd74Jw/view
![image](https://user-images.githubusercontent.com/3255203/113261122-452cad80-92f9-11eb-8e43-4d97fb8b2a40.png)

_**More information (might be useful)**
In this server has no players online. But when server is going to out of memory. I join the server. The map is loading super slow. And then everything back to normal, memory back to normal. (I think) when player going into that (problem zone) the relighting queue has been clear up?_

_**Update**
After I turn off mob farm the flush mob by water. No more memory leak!_

**Comment by LaurenceBarnes** [comment]
> Well I haven't had the issue much, but I think it is still there. I had heard purpur has redesigned the lighting system, but waited to see if paper would fix this bug. I waited a while, but it seems like it is here to stay, so I'm going to try purpur for a few days and let you all know how it goes. https://github.com/pl3xgaming/Purpur

it was Tuinity that rewrote the light engine, just sayin xD

**Comment by FarkasJoseph** [comment]
Oh good to know, thanks. I'm using yatopia now and its working wonders.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by JRoy** [comment]
> Oh good to know, thanks. I'm using yatopia now and its working wonders. Sent from ProtonMail mobile

Yeah I guess when it corrupts all your chunks there will be nothing left to light?

**Comment by electronicboy** [comment]
I pulled one of leafs patches which should resolve this issue this morning, looks like in some cases if you had no players in the world it would stop the queue from being processed properly

**Comment by AshiroKun** [comment]
I have updated to the latest build of paper at the time of posting this (#584). I am still facing the same issue as above. The server is running out of ram because the GC is not freeing any ram. I ran a heap dump to see what is causing it and it seems to be the same issue. 

![3](https://user-images.githubusercontent.com/40526576/114030806-a7922a80-9872-11eb-9fed-7d904121e17f.PNG)

My plugin list:
![2021-04-06_14 12 00](https://user-images.githubusercontent.com/40526576/114031074-ea540280-9872-11eb-959f-14b5910143dd.png)

I have a feeling the issue is to do with citizens since the server is being built and no one is on the server when this issue still happens. But I am unsure.

**Comment by electronicboy** [comment]
reopened, but, i'd be inclined to knowif others can still reproduce this, I have no real means to reproduce this in a controlled environment and the servers I do stuff for currently seem to have 0 issues here, but, we never really saw any issues even before that leaf patch was pulled

**Comment by Xeonmeister** [comment]
I had the same issue and just here to help. After testing all my plugins i figured it was mine causing this issue. Took me a little bit of time bc i ve been writing this hobby project for like 3 years now and there were lots of code i didnt even remember, and then i found this part:
if(this.world.isChunkLoaded(this.loc.getChunk()))
this is part of my custom spawner class and it s in the tick function of it, so w every spawner it runs like ~200 times every second. After deleting this part im no longer running out of memory bc of 'lightEngineThreaded'. Hope this helps.

**Comment by LoneDev6** [comment]
This probably is fixed on 1.17 because of the new light engine, right?
