### ISSUE TITLE
Paper 895 triggering NCP kick upon jumping

### ISSUE THREAD

**Issue by 0XE4** [PaperMC/Paper#453]
.

**Comment by Postremus** [comment]
We can confirm that this issue exists when you sprint and when you jump around.

**Comment by zachbr** [comment]
Seeing this all the way up to CraftBukkit. Likely related to the [SPIGOT-1903 fix](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/8e5e90d5eba3253fc7d77943b64a71d50ff1422c)

**Comment by zachbr** [comment]
Should be fixed in builds 896+

**Comment by RoboMWM** [comment]
related to https://github.com/NoCheatPlus/Issues/issues/289

I wonder if Spigot's version accounts for fixing teleportation via an End portal though, since that isn't fixed on paper's end...

**Comment by zachbr** [comment]
Still haven't been able to verify any issues with end portals...

**Comment by RoboMWM** [comment]
related issue: https://github.com/NoCheatPlus/Issues/issues/221

**Comment by zachbr** [comment]
Able to reproduce that, thanks for the link

**Comment by mibby** [comment]
Upstream seems to have reverted the commit now. Should the workaround patch be removed entirely until a proper fix is in place?

**Comment by aikar** [comment]
We had the proper logic for many many months. Spigot never wanted to pull my PR over silly reasons. They finally tried to apply my change and screwed it up causing the bug.

Z's commit was not a "work around". It was the proper fix. It restored it back to my version.
