### ISSUE TITLE
/team name color is changing the colors of the end bracket and text message as well

### ISSUE THREAD

**Issue by Psora1** [PaperMC/Paper#5327]
### What behaviour is expected:
___What you expected to see___
/team name color in chat for player's usernames
### What behaviour is observed:
___What you actually saw___
Not only the name being colored, but the second ">" and the following text message also being colored, rather than just the name itself
### Steps/models to reproduce:
___This may include a build schematic, a video, or detailed instructions to help reconstruct the issue___
1. Create a team using /team add teamname
2. Modify the team's name color using /team modify teamname color red 
3. Join that team using /team join teamname username 
4. Type any message in game chat
### Plugin list:
___A list of your plugins___
CoordinatesHUD, CoreProtect, DeepVanish, DiscordSRV, GriefPrevention, GSit, InventoryRollback, LuckPerms, OpenInv, SmoothSleep, VariableTime, WorldEdit
### Paper version:
___Paste the output of running `/version` on your server WITH the Minecraft version. `latest` is not a version; we require the output of `/version` so we can properly track down the issue.___
Paper version git-Paper-534 (MC-1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
Previous version: git-Paper-529 (MC-1.16.5)
### Anything else:
___Anything else you think may help us resolve the problem___
Paper version git-Paper-532 (MC-1.16.5) was supposed to fix bug #5307, but by doing so created this issue instead. 

Additionally, my paper.yml settings have "use-vanilla-world-scoreboard-name-coloring:" set to "true".

**Comment by kashike** [comment]
Should be fixed with the next build.

**Comment by PureVanillaFrance** [comment]
Hi ! the issue is still the same :/ now everything is white
Any possible fix ?

**Comment by Psora1** [comment]
> Hi ! the issue is still the same :/ now everything is white
> Any possible fix ?

What version of Paper are you using? At the time of writing this comment, a build hasn't been released yet fixing this according to https://papermc.io/downloads; might have to wait a little longer for a build with this bug fixed. :)

**Comment by Chew** [comment]
> Should be fixed with the next build.

So... it should be fixed _now_. If it's not working on ___the latest build___ (541 right now), let us know.

**Comment by MikaGreen1604** [comment]
I've just tested it with the latest build rn: This server is running Paper version git-Paper-543 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-506 (MC: 1.16.5) 
And it still doesn't work
