### ISSUE TITLE
ConcurrentModificationException is unhandled and causing the server to stop

### ISSUE THREAD

**Issue by arphox** [PaperMC/Paper#650]
Hello, this is a **very important issue** since it crashes the server randomly (or seems like it is random but of course it is not), please take it serious.

We are not 100% sure that this problem is caused by paper code, but it is sure that it also happened under taco. We did not use normal "spigot", only paper/taco, so we cannot say whether it still persists in basic spigot. If this bug is caused by spigot code (and not paper/taco), please forward this issue to the spigot development team.

This exception happened in total of 15 times; 1 times paper using paper (then we switched to taco not for this reason) and then times under 14 taco.

# Crash, Stacktrace

### Link/paste of stack trace

This is a part of the server log before and at the exception.
This is the oldest case where the error happened, since all other (14) exceptions were under taco version and I think you wouldn't trust it. But the problem still persists, it even happened 2 days ago too (Apr 09, 2017).

Server log (part):

___[12:08:04] [Server thread/INFO]: BanaXD discovered floor was lava___
[12:08:04] [Server thread/INFO]: athene issued server command: /tpa farkastesok3
[12:08:09] [Server thread/INFO]: BanaXD issued server command: /back
[12:08:11] [Server thread/INFO]: [m[0;37;22m[0;37;22mHerooo[m[0;32;1m » [0;37;1mKell csáki :D[m
[12:08:15] [Server thread/INFO]: farkastesok3 issued server command: /tpaccept
[12:08:17] [Server thread/INFO]: BanaXD issued server command: /home
[12:08:17] [Server thread/INFO]: Thommas issued server command: /r akk hozok
[12:08:21] [Server thread/INFO]: BanaXD issued server command: /home
[12:08:22] [Server thread/INFO]: [m[0;37;22m[0;37;22mHerooo[m[0;32;1m » [0;37;1mOksa[m
[12:08:26] [Server thread/INFO]: [Thirst] Thirst resetting on death of player BanaXD
[12:08:31] [Server thread/INFO]: [Thirst] Thirst resetting on death of player vidor
[12:08:31] [Server thread/INFO]: vidor fell from a high place
___[12:08:33] [Server thread/INFO]: BanaXD issued server command: /back___
[12:08:33] [Server thread/INFO]: [m[0;37;22m[0;37;22mTodi[m[0;32;1m » [0;37;1mHív A Söreleség!!Gyere a kocsmánkba és ha első vagy 50% Kedvezményt kapsz Itt Minden Olcsó![m
___[12:08:38] [Server thread/ERROR]: Encountered an unexpected exception
java.util.ConcurrentModificationException___
	at java.util.HashMap$HashIterator.nextNode(Unknown Source) ~[?:1.8.0_121]
	at java.util.HashMap$KeyIterator.next(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.server.v1_11_R1.EntityTracker.updatePlayers(EntityTracker.java:180) ~[spigot.jar:git-Paper-1063]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:914) ~[spigot.jar:git-Paper-1063]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) ~[spigot.jar:git-Paper-1063]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:754) ~[spigot.jar:git-Paper-1063]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:652) [spigot.jar:git-Paper-1063]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
[12:08:38] [Server thread/ERROR]: This crash report has been saved to: /home/servers/survival/./crash-reports/crash-2017-03-16_12.08.38-server.txt
[12:08:38] [Server thread/INFO]: Stopping server

### Plugin list:
The related plugin list and crash report information is not public, but I can send it through a private message to the person who will attempt fix it.
But we used "Essentials v2.0.1-b463" for teleport handling.
But I am 99% sure that this bug is not caused by a plugin since the stack trace does NOT contain any plugin name.

### Actions to reproduce (if known):
It is a very weird bug that happened randomly, but we found some correlations, like:
- all exceptions happened 5 seconds after a teleport command was used (after typing /back they have to wait 5 seconds until it really starts, so the exception is at the teleport event)
- all exceptions has correlation with a person died with the reason:
a) "suffocated in a wall"
b) "discovered floor was lava"
mostly it was because of magma block ("floor was lava"), so maybe it has something to do with magma blocks or with just blocked teleport locations.
We were able to reproduce it only a very few times, by teleporting to the places where those people died who crashed the server, for example we teleported players to a teleport trap (magma block + blocked paths side/upways) and sometimes we crashed the server, sometimes not.

### Paper build number:
"   Running: Paper version git-Paper-1063 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT) false "

# Suggestion
I would give you all the server logs and crash logs when we experienced this issue (15 times), but I won't paste them here, I would send it as a comperssed file because it is quite a lot private and contains server plugins, some infrastructure and OS information. So if you need more information, contact me.

**Comment by electronicboy** [comment]
#644 
issue is pretty much guaranteed to be a plugin doing stuff async that it shouldn't be doing async.

**Comment by arphox** [comment]
Still, if I would believe it, I have to say that if a PLUGIN can kill the server by an unhandled exception at server side, it has to be fixed at server side. You know, try{ ... } catch{...}. If you do it, the server won't stop.

Other suspicious thing: if it is a plugin, why it is unknown source?

**Comment by zachbr** [comment]
Plugins can kill the server in a myriad of ways and it is not the server's job to anticipate each and every way they can abuse internal non-documented code to do so.

Being that you haven't provided a list of plugins here, I'm closing this in favor of the existing issue.

**Comment by arphox** [comment]
Well adding a "duplicate" label will not solve the problem.
Maybe a link to another issue so I can check it's duplicate pair?

Here is the crash log, you can find the plugins there.
[crash-2017-03-16_12.08.38-server.txt](https://github.com/PaperMC/Paper/files/914587/crash-2017-03-16_12.08.38-server.txt)

Will you help now? :)

**Comment by zachbr** [comment]
Issue #644 was linked above with people having issues with AAC, supposedly the author has resolved them in the next update. I don't see that plugin on your system, unfortunately these types of issues are not necessarily simple to nail down.

You can also sort through that to see if any other plugins match from that issue.

**Comment by arphox** [comment]
Sorry, I did not notice that the (#644) text was a link, my bad.
Also, AAC = Advanced Anti Cheat plugin?
What is your suggestion to fix this problem? Disabling all plugins is not a way to go since this happens on a live server and quite rarely (we cannot reproduce it).

**Comment by zachbr** [comment]
Unfortunately that seems to mirror most everyone else's experience with this issue.

And yes, AdvancedAntiCheat is/was doing something interesting and supposedly this is resolved as of 3.1.3 but I cannot confirm that. I don't use it and am not going to buy it just to test with.
Edit: linkerino https://github.com/konsolas/AAC-Issues/issues/534

**Comment by IceString3** [comment]
The crashes still happen with 3.1.3. I'll try updating to 3.1.4 when I can, but by looking at the changelogs, I highly doubt it is fixed.
According to konsolas, there are no reports of crashes on unmodified spigot servers
