### ISSUE TITLE
Tab complete player names no longer functioning.

### ISSUE THREAD

**Issue by mibby** [PaperMC/Paper#724]
Waterfall dev 123 (MC 1.12)
Paper dev 1106 (MC 1.12)

On Paper dev 1104 (Spigot 1.11.2), with tab-complete disabled, you are still able to tab-complete player names. It only disables tab completion for commands. On Paper dev 1106 (Spigot 1.12), you are not able to tab-complete player names whatsoever. 

Spigot config.
```
commands:
  tab-complete: -1
```

**Comment by mibby** [comment]
Odd, it seems that tab-completion for names just doesn't work for /msg, /r, and similar chat commands for me. Perhaps the chat plugin itself broke.

**Comment by mibby** [comment]
I'm actually quite confused. It actually does not seem to be functioning.

* Tested Essentials ```/kick <partial name>``` - not able to tab complete.
* Tested Essentials ```/ban <partial name>``` - not able to tab complete.
* Tested DeluxeChat ```/msg <partial name>``` - not able to tab complete.
* Tested EssentialsChat alias ```/emsg <partial name>``` - not able to tab complete.
* Tested DeluxeChat ```/r <partial name>``` - not able to tab complete.
* Tested NoCheatPlus ```/ncp info <partial name>``` - able to tab complete.
* Tested McMMO ```/mcmmo inspect <partial name>``` - able to tab complete.
* Tested just typing a partial player name in chat, no command, and then hitting tab - able to tab complete.
* Tested AutoMessage ```/am bc <tab>``` - able to see available command options, despite command tab completion being disabled?

Maybe it breaks when detecting for name input after a single slash command with command based tab completion disabled, but breaks the detection for commands that are more than a single word + name?

I.e.

No command, able to tab complete player names in chat.
```/<command> <name>``` - blocks due to command detection and prevents name from being tab completed like in 1.11.2 due to a bug.
```/<command> <command> <name>``` - breaks the bug due to double syntax command before name?

**Comment by aikar** [comment]
Did it break in spigot too, or just paper?

**Comment by BillyGalbreath** [comment]
this isn't a bug, imho. I've always hated how tab complete will put a players name even for commands that didnt need it. Seems the old behavior was a bug and is now fixed.

In 1.11.2 is you return null from TabExecutor#onTabComplete it would automatically populate tab complete with online players. I was forced to return a blank List<String> on many of my plugins because of that behavior.

Edit: Well, so much for wishful thinking. I just tested this behavior and tab completes work the exact same as they have for years. I cannot reproduce this "bug" as filed.

**Comment by electronicboy** [comment]
fairly sure that somebody was talking about this issue with spigot, however would need to be confirmed, maybe a change in behavior in how this works in the server or client in 1.12?

**Comment by mibby** [comment]
@aikar This does seem to affect spigot as well.

For what it's worth, ```suggest-player-names-when-null-tab-completions: true``` doesn't fix the problem either.
https://github.com/PaperMC/Paper/commit/90b2d020918a1d18df950e360edf70d62c131b6e

**Comment by kashike** [comment]
@mibby That commit wasn't related to this issue, that commit adds a configuration option to **prevent** suggesting player names when plugins don't override tab completions.

**Comment by LogGits** [comment]
This is a problem with the essentials build. Please use the latest essentialsx build 483: https://ci.drtshock.net/job/EssentialsX

**Comment by mibby** [comment]
@LogGits But name tab-completion breaks for DeluxeChat as well, which isn't related to Essentials?

**Comment by mibby** [comment]
Updating EssentialsX seems to have fixed all partial name tab-completion for me for everything relevant to needing a name completed, so perhaps it was conflicting.

I will close this ticket unless the problem otherwise persists elsewhere.
