### ISSUE TITLE
Paper 1173 Crashing Every 5 Minutes

### ISSUE THREAD

**Issue by retrontology** [PaperMC/Paper#839]
# Performance issue

### Description of issue:
Server is crashing every 5 minutes. Seems stable until it restarts.

### Plugin list:
[https://pastebin.com/REnP2wkL](https://pastebin.com/REnP2wkL)

### Paper build number:
1173

# Incompatibility (Bug)

### What behaviour is expected:
Stable uptime
### What behaviour is observed:
Crashing every 5 minutes regardless of players online
### Steps/models to reproduce:
Install Paper-1173

# Crash, Stacktrace

### Link/paste of stack trace
[https://pastebin.com/NUd8NnzV](https://pastebin.com/NUd8NnzV)

# Suggestion
Not sure. It looks like a banner might be causing the issue?

**Comment by RoyCurtis** [comment]
Was able to reproduce this on a beta copy of our server:

* `This server is running Paper version git-Paper-1173 (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)`
* 0 plugins
* [Console log](https://gist.github.com/RoyCurtis/6cd14a405af9c582d38baf9993fae3bb)
* [Crash report](https://gist.github.com/RoyCurtis/4295964b78158f34c0bd1498885fbe20)

Seems I can make it happen sooner (60 seconds after server start) without anybody logging in, by setting `timings.history-interval` and `timings.history-length` to `10`. By setting `timings.enabled` to `false`, this crash no longer happens.

**Comment by krusic22** [comment]
I can confirm this. Also right clicking a banner while inside a protected WorldGuard region makes WG flip the F out. Also EssentialsX is throwing mad errors.

**Comment by Behoston** [comment]
+1

**Comment by zachbr** [comment]
Should be fixed in build 1174 when that gets done in a minute.
Thanks for the report

**Comment by Fonzee9** [comment]
Problem still isn't fixed https://pastebin.com/ajcMn73j and https://pastebin.com/GQPjnLPA

**Comment by electronicboy** [comment]
any form of information other than literally nothing? For all I know, you're getting hit with another issue, yet you've provided no information whatsoever on what the crash you're facing is...

**Comment by Fonzee9** [comment]
No... When i downgrade to 1172 the errors stop

**Comment by electronicboy** [comment]
What errors? You've literally yet to provide any information, I'm currently running the latest commit and I am experiencing no issues, so even if there is an issue, I cannot even consider looking into or rectifying it without any form of information.

**Comment by Fonzee9** [comment]
https://pastebin.com/ajcMn73j and https://pastebin.com/GQPjnLPA

**Comment by Fonzee9** [comment]
Those are from silkspawners and massivelag don't exist on 1172 those errors

**Comment by electronicboy** [comment]
congratulations on finally providing some form of information, Your issues are completely separate from this issue and is actually caused by Spigots modifications to the server in the BlockState replacement. Your best option is to alert the plugin developer and get them to fix their software for the latest spigot/craftbukkit release.

**Comment by Fonzee9** [comment]
But this happens with a lot of plugins!!! This is a big issue the server crashes every 5 minutes

**Comment by RoyCurtis** [comment]
FWIW, can confirm this issue is indeed fixed on b1174. Thanks!

**Comment by retrontology** [comment]
The issue is indeed fixed. Thanks everyone for the additional info and especially thanks to @Zbob750 for a quick response and update 😄
