### ISSUE TITLE
I NEED HELP paper bug commands

### ISSUE THREAD

**Issue by WhyZerVellasskx** [PaperMC/Paper#8570]
### Expected behavior

fix message unknow command

### Observed/Actual behavior

vanilla message instead of what I specified

### Steps/models to reproduce

just write the wrong command and you will see a bug

### Plugin and Datapack List

https://imgur.com/undefined

### Paper version

1.19.2

### Other

The message about the wrong command is not displayed in spigot.yml, I specified a custom message about the wrong command, and it displays the vanilla message although it should display what I specified

https://imgur.com/p3XgWfB photo bug
https://imgur.com/undefined spigot.yml

**Comment by Machine-Maker** [comment]
Probably fixed by https://github.com/PaperMC/Paper/pull/8232

**Comment by WhyZerVellasskx** [comment]
no

**Comment by WhyZerVellasskx** [comment]
I downloaded your latest kernel version and the bug remained

**Comment by EterNityCH** [comment]
It's not merged yet. You can subscribe to the issue Machine provided so you get an update when it does.

**Comment by WhyZerVellasskx** [comment]
ok

**Comment by Owen1212055** [comment]
Duplicate of https://github.com/PaperMC/Paper/issues/8329
